### ISSUE TITLE
Разработать спецификации для протоколов передачи данных

### ISSUE THREAD

**Issue by None-stopCoding** [Students-of-the-city-of-Kostroma/trpo_automation#1]
Есть документация по API

**Comment by YuriSilenok** [comment]
> Есть документация по API

Если вы сделали документацию, то нужно прикреплять ссылку к документу. 
Иначе из этой задачи не найти документ.
если вы делали эту задачу, то должны ее назначить на себя в поле Assigness.
если эта задача завершена, ее нужно закрыть

**Comment by None-stopCoding** [comment]
В ближайшее время мы приведем в порядок и автоматизируем процесс разработки

**Comment by TsaplinK** [comment]
По полученному API от почтового сервиса спроектировать методы приема /ответа сервиса проверок

**Comment by YuriSilenok** [comment]
Какие есть изменения по этой задаче?

**Comment by YuriSilenok** [comment]
Почему нет активности по этой задаче?

**Comment by None-stopCoding** [comment]
Задача не имеет смысл, так как создавалась в начале проекта, когда не было полного понимание, что делаем
