### ISSUE TITLE
Исправить баг в файле main_2_base_WorkWithLetters

### ISSUE THREAD

**Issue by SkinnerX7** [Students-of-the-city-of-Kostroma/trpo_automation#10]
В проекте появилось новое состояние письма

- Ссылка на ресурсы некорректна

В связи с этим добавить обработку этого состояния в код проекта в файл main_2_base_WorkWithLetters в функцию LettersConvertToString

**Comment by Progoger** [comment]
Исправил баг
Если ссылка в письме некорректна, то меняю код статус письма на "08"

**Comment by YuriSilenok** [comment]
В ветке issue-10 давно не было активности

**Comment by YuriSilenok** [comment]
В ветке issue-10 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. Вы не удалили ветку issue-10 и закрыли задачу

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-10 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-10 давно не было активности
