### ISSUE TITLE
Переделать сценарии на функцию ValidateLetters

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#104]
Раскрыть подробно объекты (выписать все ключевые важные, требующиеся для работы функции или изменяющиеся в ней поля) в столбце Inputs
Ссылка на [документ](https://docs.google.com/spreadsheets/d/1IHaHZS0_vT2SRZCWRdLPDvhNNvPcKf5QjA6GztFQgF4/edit?usp=sharing)

**Comment by cyberAndrey** [comment]
Задание выполнено
