### ISSUE TITLE
Python и TCP

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#107]
Разработать методы для взаимодействия вашего модуля и  модулей проверки заданий
Стандартом работы является TCP соединение

Для этого:

- Изучить [запись](https://wiki.python.org/moin/TcpCommunication) по TCP коммуникациям в python

- Изучить [статью](https://habr.com/ru/post/149077/) по сокетам в python

- Изучить [статью](https://overcoder.net/q/755859/%D0%BA%D0%B0%D0%BA-%D0%BE%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82-json-%D1%81-%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C%D1%8E-%D1%81%D0%BE%D0%BA%D0%B5%D1%82%D0%B0-tcp-%D0%B2-python) по отправке JSON в TCP

- Изучить [видео](https://www.youtube.com/watch?v=MPjgHxK8k68) по взаимодействию клиент-серверного приложения на TCP

- На основании изученных материалов + интернет эмулировать работу TCP соединения

- - Написать модуль, отвечающий за клиентскую часть

- - Написать модуль, отвечающий за серверную часть

- - Показать их взаимодействие путём отправки и получения данных клиентом с сервера

- - - Отправить данные в строковом формате
- - - Получить данные в строковом формате
- - - Отправить json с данными
- - - Получить json с ответом

Результаты представить в виде двух модулей на языке python. В клиентской части должны быть 4 метода, реализующие необходимый по задаче функционал по взаимодействию модулей.

**Comment by SkinnerX7** [comment]
Написал серверный и клиентский модули
Ветка issue-107

**Comment by urec-programmec** [comment]
Pull reqest принят
Задача закрывается
