### ISSUE TITLE
Функция LettersConvertToString() возвращает из репозитория ФИ, однако в проекте все студенты имеют ФИО 

### ISSUE THREAD

**Issue by SkinnerX7** [Students-of-the-city-of-Kostroma/trpo_automation#109]
Проблема заключается в том, что в проекте все студенты значатся как ФИО, однако когда студенты будут заливать свои файлы на гит, то могут написать только ФИ. Поэтому есть два решения проблемы: извлекать внутри метода LettersConvertToString() фамилию и имя или дописать правила оформления файлов на гите

**Comment by Progoger** [comment]
Можете пояснить в чём заключается баг и продемонстрировать его?

**Comment by YuriSilenok** [comment]
Заголовок бага не должно указывать что нужно сделать, оно должно отвечать на три вопроса.
Что не работает?
Где не работает?
Когда не работает?
Соответственно без упоминания слова не работает. А содержимое бага должен содержать сценарий позволяющий воспроизвести сбой. А так же набор данных получаемых при этом. Скрины, логи и т.д.

**Comment by YuriSilenok** [comment]
Какие есть обновления по этой задаче?

**Comment by SkinnerX7** [comment]
Были доработаны правила оформления ссылок и файлов на гите, поэтому задачу можно закрыть, бага нет

**Comment by YuriSilenok** [comment]
> Заголовок бага не должно указывать что нужно сделать, оно должно отвечать на три вопроса.
> Что не работает?
> Где не работает?
> Когда не работает?
> Соответственно без упоминания слова не работает. А содержимое бага должен содержать сценарий позволяющий воспроизвести сбой. А так же набор данных получаемых при этом. Скрины, логи и т.д.


Пожалуйста, исправьте замечания.

**Comment by SkinnerX7** [comment]
Были доработаны правила оформления ссылок и файлов на гите, поэтому задачу можно закрыть, бага нет

**Comment by YuriSilenok** [comment]
> > Заголовок бага не должно указывать что нужно сделать, оно должно отвечать на три вопроса.
> > Что не работает?
> > Где не работает?
> > Когда не работает?
> > Соответственно без упоминания слова не работает. А содержимое бага должен содержать сценарий позволяющий воспроизвести сбой. А так же набор данных получаемых при этом. Скрины, логи и т.д.
> 
> Пожалуйста, исправьте замечания.

Вы закрыли задачу без исправления, почему?

**Comment by SkinnerX7** [comment]
Я исправил название и описание 10 дней назад

**Comment by YuriSilenok** [comment]
Я написал вам мене чем через 24 часа после закрытия задачи.
Функция такая-то  возвращает неожиданный результат, если пользователь указал только имя и фамилию в отправленном репозитории. Приблительно такой должен быть заголовок бага. Что где когда не работает. Чётко прослеживается. В чем трудность следовать инструкциям?

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Я не понимаю почему была закрыта задача.

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by SkinnerX7** [comment]
Почему эта задача открывается? Вопрос был решен путем добавления в документ инструкции как правильно оформлять файлы в репозитории

**Comment by YuriSilenok** [comment]
Думаю мы можем закрыть ее так как семестр завершен и нет время объяснять требования к багам
