### ISSUE TITLE
Разработать документацию для работы с данными в формате JSON

### ISSUE THREAD

**Issue by ComButterbrot** [Students-of-the-city-of-Kostroma/trpo_automation#11]
Необходимо описать протокол передачи данных в формате JSON и ключи передачи в соответствии с общей задачей.

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте ссылку на документация, если Вам нужно что бы я проверил, то назначте меня в ответственных с соответствующим комментарием,

**Comment by ComButterbrot** [comment]
Ссылка на документацию доступна [здесь](https://drive.google.com/folderview?id=1ax4_BVRX6Tjtlypt7YU5KuNpSsFyFGTa).
Файл называется "Описание протокола передачи данных".

**Comment by YuriSilenok** [comment]
Ссылка должна вести на документ, а не на папку

**Comment by YuriSilenok** [comment]
Оставил несколько комментариев в документе
если неизвестно что писать в томи или ином случае, то для этиого все равно должен быть каркас. Не увидел ответ на получание лабораторной работы. а так же не увидел описание протокола для выставления оценки в журнал

**Comment by YuriSilenok** [comment]
если задача в статусе Done, почему она открыта?

**Comment by Svyat935** [comment]
Задача закрыта в связи с её выполнением.
