### ISSUE TITLE
Добавить правила ссылок на ресурсы

### ISSUE THREAD

**Issue by SkinnerX7** [Students-of-the-city-of-Kostroma/trpo_automation#11]
Неоднозначны правила ссылок на ресурсы

- Максим - сформулируй их как тот, кто знает правила прикрепления файлов в репозиторий

- Андрей - внеси в [документ](https://docs.google.com/document/d/1YMtlwsImBzR1ONhY6hH0VZnonpRmHM9UZ0glsG8sMLA/edit?usp=sharing)

**Comment by Progoger** [comment]
Файл написан, ожидает проверки: https://drive.google.com/open?id=1yfVSkWyUUPvF0am4xv9aU-zMeoq3EdUBfSxAPWvCxP0

**Comment by Progoger** [comment]
Файл написан и ожидает проверки (https://docs.google.com/document/d/1yfVSkWyUUPvF0am4xv9aU-zMeoq3EdUBfSxAPWvCxP0/edit?usp=sharing)

**Comment by urec-programmec** [comment]
Макс 
Задачу принял
Андрей
Внеси в документ по правилам написания писем

**Comment by cyberAndrey** [comment]
Изменения [внесены](https://docs.google.com/document/d/1YMtlwsImBzR1ONhY6hH0VZnonpRmHM9UZ0glsG8sMLA/edit)

**Comment by urec-programmec** [comment]
@cyberAndrey 
Не нашёл в твоём документе материалов из  [этого](https://docs.google.com/document/d/1yfVSkWyUUPvF0am4xv9aU-zMeoq3EdUBfSxAPWvCxP0/edit?usp=sharing) 
Внести нужно было правила ссылок на ресурсы
