### ISSUE TITLE
Заполнение документа-отчета по unittest'ам 

### ISSUE THREAD

**Issue by SkinnerX7** [Students-of-the-city-of-Kostroma/trpo_automation#111]
- Заполнить статистику по unittest'ам
- Bug report
- Проверить соответствие сценариев и тестов, заполнить баги в сценариях

**Comment by SkinnerX7** [comment]
@urec-programmec, проверь заполнение [документа](https://docs.google.com/spreadsheets/d/1IHaHZS0_vT2SRZCWRdLPDvhNNvPcKf5QjA6GztFQgF4/edit#gid=208599158)

**Comment by urec-programmec** [comment]
Задача принята
