### ISSUE TITLE
Запуск программы Python в качестве службы Ubuntu

### ISSUE THREAD

**Issue by ShapovalovQ** [Students-of-the-city-of-Kostroma/trpo_automation#115]
Мне нужно подготовить документацию (подготовить теорию), в которой содержится информация о том, как из программы Python реализовать службу в Ubuntu.

**Comment by ShapovalovQ** [comment]
https://docs.google.com/document/d/1dWNlsbyRJFYibmpcPZ5xLk5pPMggd24E4CzrP3LijgU/edit

**Comment by Svyat935** [comment]
@ShapovalovQ  Как состояние задачи ?

**Comment by ShapovalovQ** [comment]
В процессе

**Comment by ShapovalovQ** [comment]
Сделал [документацию](https://docs.google.com/document/d/1dWNlsbyRJFYibmpcPZ5xLk5pPMggd24E4CzrP3LijgU/edit?usp=sharing). Прошу проверить.

**Comment by Svyat935** [comment]
Задача выполнена
