### ISSUE TITLE
Список экземпляров класса Letter

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#116]
Разработать метод, работающий непосредственно с поступающими с почты письмами
Метод должен использоваться для заполнения списка экземпляров класса Letter

- Что на вход
Сырые данные по письмам, вытащенные с почты

- Что требуется
Составить список экземпляров класса Letter по спецификации в [диаграмме](https://www.draw.io/#G1uBk9EZCwKGp3pa4MURUgB9tz5a2x9DN_)

- Что предусмотреть
- - Заполнение поля User экземпляром класса User
- - Body = чистое тело письма

Результаты представить в виде модуля на языке  python

**Comment by VladmirV** [comment]
Создание ветки "issue-116".

**Comment by VladmirV** [comment]
Добавление первичного скрипта с неполным функционалом.

**Comment by VladmirV** [comment]
Задержка pull request. 
Причины:
1. Трудность с поиском информации о парсинге "Body" писем.
2. Морально-психологическая надорванность, вызванная ложной информацией о закрытии учебного заведения на карантин.

**Comment by urec-programmec** [comment]
Информацию принял.
Вакцины нет, но вы держитесь. 

До встречи на у д а л ё н к е

**Comment by VladmirV** [comment]
Проблема с декодированием решена. Возникли новые проблемы:
1. Лишние дублирования писем.
2. Ошибки при попытке декодировать письмо с вложениями.
Проводится работа по устранению ошибок.

**Comment by VladmirV** [comment]
@urec-programmec 
На текущий момент загружена промежуточная версия. Работа приостановлена до внесения правок в классы Letter и User. Есть несколько оптимизационных вопросов, которые необходимо будет обсудить при личной встрече.

**Comment by VladmirV** [comment]
@urec-programmec 
Возможно не успею к концу спринта.
Вышел на улицу в карантин, заразился аппендицитом.

**Comment by urec-programmec** [comment]
Задача закрывается за потерей актуальности
