### ISSUE TITLE
Ошибка при импорте из google.py

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/trpo_automation#117]
При тестировании методов из файла google.py (18-ISbo-2a/email/18-ISbo-2a) возникает следующая ошибка:
![image](https://user-images.githubusercontent.com/55210615/76404659-dc922c00-6397-11ea-9e5d-8cd697072457.png)
Если переименовать файл google и исправить импорт, ошибка не возникает.

**Comment by Svyat935** [comment]
@Sirokko77 назначается исправить данный баг.

**Comment by Svyat935** [comment]
Баг исправлен.
