### ISSUE TITLE
Баг в файле main_2_WorkWithLetters в методе LettersConvertToString() с полем Body

### ISSUE THREAD

**Issue by Progoger** [Students-of-the-city-of-Kostroma/trpo_automation#119]
Баг в методе LettersConvertToString() файла main_2_WorkWithLetters. Сценарий test_S_4_t4 отрабатывает неверно. Описание - проверка письма с ссылкой не на ту папку( с другой лабораторной). Результатом должно быть - Объект класса Letter, если в папке есть файл с ФИО студента, тогда в поле Body код программы для другой лабораторной, иначе с теми же параметрами. В результате теста поле Body становится пустым.

**Comment by YuriSilenok** [comment]
Заголовок бага не должно указывать что нужно сделать, оно должно отвечать на три вопроса.
Что не работает?
Где не работает?
Когда не работает?
Соответственно без упоминания слова не работает. А содержимое бага должен содержать сценарий позволяющий воспроизвести сбой. А так же набор данных получаемых при этом. Скрины, логи и т.д.
