### ISSUE TITLE
Написать единую документацию по ЛР

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#120]
Написать документ, в котором будут чётко описаны все задания по каждой ЛР.
Речь идёт не о конкретных вариантах в цифрах или кусках классов, а о задании в целом в рамках курса "Дисциплина ТРПО"

Результаты представить в виде документа на [GD](https://drive.google.com/drive/folders/1z9DwdZ6ETedAGSBkTFUHI1MOGeoRJg35)

**Comment by YuriSilenok** [comment]
@urec-programmec мы не договривались на разработку вариантов, а договаривались на разработку ТЗ. Разработкой вариантов занимаются группы ВТ. Пересмотри границу того, что будет делать твоя команда.

**Comment by urec-programmec** [comment]
@YuriSilenok это задача не на каждый из вариантов в отдельности, а на общие задания для каждой ЛР, которые соответствуют курсу "ТРПО"

**Comment by YuriSilenok** [comment]
> @YuriSilenok это задача не на каждый из вариантов в отдельности, а на общие задания для каждой ЛР, которые соответствуют курсу "ТРПО"

Привет @urec-programmec 

Этим занимаются группы ВТ, изготовлением общего задания и вариантов к ним.

Спасибо,
Юрий

**Comment by YuriSilenok** [comment]
делегировано на ВТ
