### ISSUE TITLE
Удалить токен

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#121]
Удалить токен безопасности последнего коммита и pull request ветки issue-23
Задача #23
Pull [request](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/pull/105#issue-385912045)

Варианты решения:
- Откатиться по коммитам до последнего без него
Тут думаю проще всего будет тебе, т.к. ты уже умеешь  работать с git

- Переполучить другой токен безопасности Google если это возможно.

- Создать и перенастроить аккаунт Google. Это самый по моему худший случай. Так что удачи.

**Comment by CatherinePRO** [comment]
закрыт доступ по старому токену

**Comment by CatherinePRO** [comment]
создан новый токен

**Comment by CatherinePRO** [comment]
запрошена отмена выпуска

**Comment by urec-programmec** [comment]
Отмена проведены. 
По результатам pull request задача закрывается
