### ISSUE TITLE
Баг в FormListWithLetters с письмом с вложениями

### ISSUE THREAD

**Issue by SkinnerX7** [Students-of-the-city-of-Kostroma/trpo_automation#123]
Обработка курсивного письма перекрывает функционал работы с вложениями

**Comment by YuriSilenok** [comment]
Убрать версию из заголовка, описание оформить как положено

**Comment by VladmirV** [comment]
Закрыто по причине потери актуальности.
Баг перекрыт функционалом задачи #25
