### ISSUE TITLE
Баг в FormListWithLetters письмо только с цифрами/символами в теле 

### ISSUE THREAD

**Issue by SkinnerX7** [Students-of-the-city-of-Kostroma/trpo_automation#124]
Исправить баг с письмом, в котором только цифры/символы в теле

**Comment by YuriSilenok** [comment]
В заголовке не указывают версию, для этого есть описание, комментарии и обязательно метки

**Comment by YuriSilenok** [comment]
Не нужно писать что что-то нужно исправить. Вы просто описываете квочпроищвести сбой и если возможно описываете рбзоднрй сценарий

**Comment by VladmirV** [comment]
Закрыто по причине потери актуальности.
Баг перекрыт функционалом #25
