### ISSUE TITLE
Реализовать архивацию писем

### ISSUE THREAD

**Issue by 0Meridian0** [Students-of-the-city-of-Kostroma/trpo_automation#130]
Получить доступ к labels 
Исправить ошибку 403

**Comment by Svyat935** [comment]
@0Meridian0 Как состояние задачи ?

**Comment by 0Meridian0** [comment]
@Svyat935 В поиске информации. Ср-Чт точно будет готова

**Comment by 0Meridian0** [comment]
SCOPES = ['https://www.googleapis.com/auth/gmail.readonly','https://www.googleapis.com/auth/gmail.send', 'https://www.googleapis.com/auth/gmail.labels', 'https://www.googleapis.com/auth/gmail.modify']
не сработало, попробую дать полный доступ

**Comment by 0Meridian0** [comment]
SCOPES = ['https://mail.google.com/']
не сработало, попробую дать область metadata(Читайте метаданные ресурсов, включая метки, записи истории и заголовки сообщений электронной почты, но не тело сообщения или вложения.)

**Comment by 0Meridian0** [comment]
SCOPES = ['https://www.googleapis.com/auth/gmail.readonly','https://www.googleapis.com/auth/gmail.send', 'https://www.googleapis.com/auth/gmail.labels', 'https://www.googleapis.com/auth/gmail.modify', 'https://www.googleapis.com/auth/gmail.metadata']
программа получила ошибку доступа раньше чем мы обратились к ярлыкам, значит последняя область мешает работе
попробуем убрать "ограниченные области" типа "metadata"&"modify"

**Comment by 0Meridian0** [comment]
SCOPES = ['https://www.googleapis.com/auth/gmail.readonly','https://www.googleapis.com/auth/gmail.send', 'https://www.googleapis.com/auth/gmail.labels']
Ошибка выпадает в том же месте(при попытке сменить ярлык)

**Comment by 0Meridian0** [comment]
@Svyat935 случайно залил задачу вместе с другой. Архивация теперь работает, проверить код можно [здесь](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/pull/235)
