### ISSUE TITLE
Исправить ссылки в коде

### ISSUE THREAD

**Issue by 0Meridian0** [Students-of-the-city-of-Kostroma/trpo_automation#131]
Исправить ссылки(изменив общедоступную ссылку на ограниченную по доступу)

**Comment by Svyat935** [comment]
@0Meridian0 Как состояние задачи ?

**Comment by 0Meridian0** [comment]
@Svyat935 В поиске информации. Ср-Чт точно будет готова

**Comment by 0Meridian0** [comment]
@Svyat935 если я хочу изменить структуру проекта, то мне надо новую задачу писать?

**Comment by 0Meridian0** [comment]
@Svyat935 можно ли сделать ссылку в роде [этой](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/issues/131), но в gmail. я не нахожу таких функций. Либо мне надо просто изменить ссылки на доступные только людям имеющим эту ссылку?
