### ISSUE TITLE
Составить пользовательский сценарий.

### ISSUE THREAD

**Issue by MaJishpro** [Students-of-the-city-of-Kostroma/trpo_automation#132]
Подразумевается,  что с точки зрения пользователя ты делаешь, и что получаешь после выполнения всех модулей.

**Comment by MaJishpro** [comment]
Добавил пример сценария.
https://drive.google.com/file/d/1UxsDcVl95DzXizePlJF8Ji7CrqDzVyl3/view?usp=sharing

**Comment by Svyat935** [comment]
Задача выполнена
