### ISSUE TITLE
Написание логирования

### ISSUE THREAD

**Issue by cyberAndrey** [Students-of-the-city-of-Kostroma/trpo_automation#135]
Создание логов для функций по [этим](https://docs.google.com/spreadsheets/d/1_0wGJbMO4SctmNRMTFkDYaOhgvOVKfpT8hklMQCNxEg/edit#gid=0) правилам
Файл логов создается на каждую итерацию цикла
Файлы логов стираются из папки каждые 24 часа

**Comment by cyberAndrey** [comment]
По заданию предусматривалась реализация уровней debug & info
принцип работы описан [здесь](https://docs.google.com/document/d/1LJK7G0RX6O27gQQrrbMjcyPpTepc0KcdY-CICCTqH3M/edit)

**Comment by YuriSilenok** [comment]
> Файлы логов стираются из папки каждые 24 часа

Могу предложить не удалять логи, а давать им названия текущего дня.
Таким образом будет возможность получить логи если проблема обнаружиться на следующий день и позднее.

**Comment by YuriSilenok** [comment]
И мне из описания задачи не совсем понятно, в результате реализации этой задачи будет только документ или код или можеь быть план по которому было бы понятно что нужно покрыть и что уже покрто, если что-то покрыто.

**Comment by cyberAndrey** [comment]
Хорошая идея не удалять их, сделаю через нумерацию дня
Будет код, а что им покрывать нужно решать совместно

**Comment by urec-programmec** [comment]
Задача принята

**Comment by YuriSilenok** [comment]
Добрый день. Вы не удалили ветку issue-135 и закрыли задачу

**Comment by cyberAndrey** [comment]
> Добрый день. Вы не удалили ветку issue-135 и закрыли задачу

Увидел, исправил
