### ISSUE TITLE
Инсталятор для проекта.

### ISSUE THREAD

**Issue by Svyat935** [Students-of-the-city-of-Kostroma/trpo_automation#136]
В корне проекта лежит файл install.sh
Пользователь должен его скрыть самостоятельно и запустить для дальнейшей установки. Об этом должно быть написано в файле readmy.md в репозитории.

В папке где запускается скрипт install.sh скрипт проверяет что существует папка releases. Если она отсутствует, она должна быть создана.

Если установка первая, то есть в папке releases нет папок, то скрипт должен получить номер последней версии и создать папку с таким именем. 

Если в папке releases есть, то нужно получить последний установленный номер и сравнить с номером последнего релиза на гитхаб. Если на гитхаб релиз более новый. То нужно создать в папке releases папку с именем релиза на гитхаб.

В папку с новым релизом нужно скачать релиз, который запакован в виде архива release.zip.

Архив должен быть распаковал в папку нового релиза. В нем должен содержаться скрипт инсталирубщий компоненты системы, назовём его installBuild.sh. Он в свою очередь должен:
- корректно остановить работу всех служб
- вызвать скрипты инсталяторы для каждого компонента.
- запустить все службы в корректно порядке.

После завершения работы скрипта installBuild.sh, скрипт install.sh должен проверить что запись в cron существует и настроена по умолчанию на проверку релиза каждую ночь. Cron должен запускать каждую ночь скрипт install.sh.
Проверить что существует настройка запуска скрипта install.sh при запуске системы.

**Comment by YuriSilenok** [comment]
Метка для этой задачи означает что инсталятор должен будет развернуть версию 0.0.0.7 ?

**Comment by Svyat935** [comment]
> 
> 
> Метка для этой задачи означает что инсталятор должен будет развернуть версию 0.0.0.7 ?

В данный момент да. При нужно потом можно будет привязать следующий пре-релиз.

**Comment by YuriSilenok** [comment]
Добавил описание к задаче
---
# Алгоритм работы инсталятора
- Получить номер версии установленного ПО
- Получить номер последней версии на github
- Если версия на гитхаб более новая, то
- - Скачать новую версию с гитхаб
- - Корректно остановить работку ПО
- - Распаковать и установить новую версию
- - Запустить работу всех сервисов
- Проверить автозапуск системы при старте системы. Если автозапуска нет, запланировать его.

**Comment by DanilKozlov00** [comment]
Возможный принцип работы инсталятора: 
Есть общий скрипт, допустим installer.sh, лежит в корне репозитория. Он скачивает последний source_code.zip релиза и расспаковывает его в папке загрузок. Затем поочередно запускается 4 скрипта, каждой команды. Они выполняют требуемые для работы каждого модуля действия и запускают 4 службы. По окончанию работы всех 4 скриптов, запускается еще один, который должен установить службу необходимую для проверки обновлений. Папка проекта удаляется.
Служба обновлений должна с какой-то периодичностью проверять наличие новой версии на гите, если такая появилась, то необходимо скачать ее,распаковать, остановить все 4 службы команд, перезаписать/обновить файлы, запустить службы команд заново. Удалить скачанные файлы

**Comment by YuriSilenok** [comment]
> Возможный принцип работы инсталятора: 
> Есть общий скрипт, допустим installer.sh, лежит в корне репозитория. Он скачивает последний source_code.zip релиза и расспаковывает его в папке загрузок. Затем поочередно запускается 4 скрипта, каждой команды. Они выполняют требуемые для работы каждого модуля действия и запускают 4 службы. По окончанию работы всех 4 скриптов, запускается еще один, который должен установить службу необходимую для проверки обновлений. Папка проекта удаляется.
> Служба обновлений должна с какой-то периодичностью проверять наличие новой версии на гите, если такая появилась, то необходимо скачать ее,распаковать, остановить все 4 службы команд, перезаписать/обновить файлы, запустить службы команд заново. Удалить скачанные файлы
> 

Нет, все не так, я же сказал, нет службы котороя следит за обновлениями. Вскоре опишу ниже другой вариант как это может работать.

**Comment by YuriSilenok** [comment]
В корне проекта лежит файл install.sh
Пользователь должен его скрыть самостоятельно и запустить для дальнейшей установки. Об этом должно быть написано в файле readmy.md в репозитории.

В папке где запускается скрипт install.sh скрипт проверяет что существует папка releases. Если она отсутствует, она должна быть создана.

Если установка первая, то есть в папке releases нет папок, то скрипт должен получить номер последней версии и создать папку с таким именем. 

Если в папке releases есть, то нужно получить последний установленный номер и сравнить с номером последнего релиза на гитхаб. Если на гитхаб релиз более новый. То нужно создать в папке releases папку с именем релиза на гитхаб.

В папку с новым релизом нужно скачать релиз, который запакован в виде архива release.zip.

Архив должен быть распаковал в папку нового релиза. В нем должен содержаться скрипт инсталирубщий компоненты системы, назовём его installBuild.sh. Он в свою очередь должен:
- корректно остановить работу всех служб
- вызвать скрипты инсталяторы для каждого компонента.
- запустить все службы в корректно порядке.

После завершения работы скрипта installBuild.sh, скрипт install.sh должен проверить что запись в cron существует и настроена по умолчанию на проверку релиза каждую ночь. Cron должен запускать каждую ночь скрипт install.sh.
Проверить что существует настройка запуска скрипта install.sh при запуске системы.

**Comment by magnitola** [comment]
Я не знаю, как написать правильно файл install.sh, чтобы он полностью соответствовал всем вашим требованиям. Прочитал в интернете по этой теме много материала, но так и не понял, как правильно сделать большинство действий.

**Comment by YuriSilenok** [comment]
Конкретезируйте проблему, пока непонятна её суть.

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.
