### ISSUE TITLE
Диаграмма последовательности

### ISSUE THREAD

**Issue by Sirokko77** [Students-of-the-city-of-Kostroma/trpo_automation#137]
Необходимо реализовать диаграмму последовательности, в которой будет отражено взаимодействие всех компонентов программы.

**Comment by Svyat935** [comment]
@Sirokko77 Как состояние задачи ?

**Comment by Sirokko77** [comment]
Задача в процессе, диаграмма почти закончена

**Comment by Sirokko77** [comment]
Задача выполнена [Посмотреть тут](https://drive.google.com/file/d/1vP5poMqukWCco8qLhCVHXQfLySdUPErT/view?usp=sharing)

**Comment by Svyat935** [comment]
Задача выполнена.
