### ISSUE TITLE
Падает ошибка в main.py при обращении к pattern.py

### ISSUE THREAD

**Issue by Svyat935** [Students-of-the-city-of-Kostroma/trpo_automation#137]
Узнать в чем проблема падения при отправки письма в main.py. 

Стоит заметить: падение происходит после обращение к pattern. Вероятно дело добавление новой переменной.

**Comment by YuriSilenok** [comment]
Зависит ли это от текста письма, если да, то стоит привести пример того, что отправляется.
Если вы наблюдали падение на локальном энве, хорошо прикрепить логи

**Comment by 0Meridian0** [comment]
проблема кроется в том, что словарь валидации просто не передается
![image](https://user-images.githubusercontent.com/54988303/83451141-2a7e7380-a45f-11ea-9e19-6c2883cb25c9.png)
![image](https://user-images.githubusercontent.com/54988303/83451159-32d6ae80-a45f-11ea-8bec-9a23bb23607e.png)
