### ISSUE TITLE
Настроить непрерывную интеграцию

### ISSUE THREAD

**Issue by SkinnerX7** [Students-of-the-city-of-Kostroma/trpo_automation#14]
Решить вопрос с шифрованием файлов доступа (конфиги, токены) с А группой

Настроить CI за этот спринт или найти аналог качественного тестирования

Постоянное информирование приветствуется

**Comment by YuriSilenok** [comment]
Какие есть обновления по этой задаче?

**Comment by YuriSilenok** [comment]
В ветке issue-14 давно не было активности

**Comment by YuriSilenok** [comment]
В ветке issue-14 давно не было активности

**Comment by YuriSilenok** [comment]
Какие есть обновления по этой задаче?

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-14 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-14 давно не было активности

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-14 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-14 давно не было активности

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.
