### ISSUE TITLE
Разработать шаблон для решения лабораторных работ по паттерну Стратегия

### ISSUE THREAD

**Issue by TsaplinK** [Students-of-the-city-of-Kostroma/trpo_automation#14]
Реализовать тестовую версию
#13 - Ссылка на задачу

**Comment by AnastasiVokhmyanina28** [comment]
[Strategy-master.zip](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/files/4250227/Strategy-master.zip)

**Comment by YuriSilenok** [comment]
вы создали проект и прикрепили его к этой задаче. Это хорошо, но не идеально, возникнет проблема, откуда будет Ваш компонент брать эти шаблоны? думаю он должен размещен в репозитории в подкаталоге каталога LR07

**Comment by YuriSilenok** [comment]
А почему задачу закрыл отличный человек от ответственного? Если эту задачу кто-то проверяет и после проверки должны закрыть ее, то нужно перевесить на этого человека для закрытия

**Comment by None-stopCoding** [comment]
За закрытие задач отвечает наш task-manager - Костя Цаплин, он закрыл задачу. Zip файл уже добавляется в папку на гугл диске. Спасибо.

**Comment by YuriSilenok** [comment]
> За закрытие задач отвечает наш task-manager - Костя Цаплин, он закрыл задачу. Zip файл уже добавляется в папку на гугл диске. Спасибо.

файл zip не найден на гугл диске

**Comment by AnastasiVokhmyanina28** [comment]
данная задача была поставлена , когда не было полного понимания того, что нужно было сделать. на данный момент является не актуальной. похожая задача реализуется здесь: #214
