### ISSUE TITLE
Составить список рекомендации по организации кода

### ISSUE THREAD

**Issue by TsaplinK** [Students-of-the-city-of-Kostroma/trpo_automation#15]

**Comment by None-stopCoding** [comment]
[Рекомендации для код ревью](https://docs.google.com/document/d/19Qf2eQCrAhQCHDadIgdWVq4mtCPDfXSduzHvf7VgFy0/edit?usp=sharing)

**Comment by YuriSilenok** [comment]
заменить ссылку на файл действительной, текущая ссылка ведет на файл не расположенный в общей папке.

**Comment by None-stopCoding** [comment]
Ссылка заменена

**Comment by YuriSilenok** [comment]
Почему задача все еще открыта?
