### ISSUE TITLE
Тестирование релиза v.0.0.0.8

### ISSUE THREAD

**Issue by SkinnerX7** [Students-of-the-city-of-Kostroma/trpo_automation#154]
Что необходимо:
- тестирование нового релиза всеми тестами, подготовка отчёта о тестировании, отчёта о покрытии

**Comment by SkinnerX7** [comment]
Архив с покрытием проекта
[Покрытие_v.0.0.0.8_(08.06.2020).zip](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/files/4747529/_v.0.0.0.8_.08.06.2020.zip)

**Comment by SkinnerX7** [comment]
![image](https://user-images.githubusercontent.com/55276061/84061519-b7c54900-a9c6-11ea-980a-f774089fb126.png)

**Comment by SkinnerX7** [comment]
[Ссылка на документ с итогами по тестированию](https://docs.google.com/spreadsheets/d/1IHaHZS0_vT2SRZCWRdLPDvhNNvPcKf5QjA6GztFQgF4/edit)

**Comment by YuriSilenok** [comment]
> [Документ](https://docs.google.com/spreadsheets/d/1IHaHZS0_vT2SRZCWRdLPDvhNNvPcKf5QjA6GztFQgF4/edit)

я не забыл про эту задачу, дайте корректное название этому документу
