### ISSUE TITLE
Покрытие функций логированием

### ISSUE THREAD

**Issue by cyberAndrey** [Students-of-the-city-of-Kostroma/trpo_automation#157]
Оформить логирование всех имеющихся функций проекта

**Comment by cyberAndrey** [comment]
Задание выполнено. Ожидается локальное тестирование Сережей

**Comment by SkinnerX7** [comment]
[trpo_automation.zip](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/files/4742218/trpo_automation.zip)

**Comment by YuriSilenok** [comment]
> [trpo_automation.zip](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/files/4742218/trpo_automation.zip)

могли бы пояснить, что за файл вы прикрепили, некультурно так делать

**Comment by cyberAndrey** [comment]
Задание выполнено

**Comment by YuriSilenok** [comment]
Добрый день. Вы не удалили ветку issue-157 и закрыли задачу
