### ISSUE TITLE
Функциональное тестирование сервера

### ISSUE THREAD

**Issue by None-stopCoding** [Students-of-the-city-of-Kostroma/trpo_automation#159]
# Срок сдачи: 21.04.20
### Epic: #209
_Пояснения_: не требуются

**Comment by leshastern** [comment]
Текущий прогресс по задаче тут: [Ссылка](https://docs.google.com/spreadsheets/d/1lbYraedf03kPdlvMH0Iv_QTpAkXsVawn03gtBDR1ngo/edit?usp=sharing)

**Comment by None-stopCoding** [comment]
@leshastern всегда пиши причину, почему закрыл)
