### ISSUE TITLE
Сценарии тестирования функции MakeAnswersForUsers

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#16]
Написать сценарии тестирования функции SendLetters по аналогии с уже существующими в [документе](https://docs.google.com/spreadsheets/d/1IHaHZS0_vT2SRZCWRdLPDvhNNvPcKf5QjA6GztFQgF4/edit?usp=sharing)
- Входные данные должны быть разного типа (как принимаемые для обработки этой функцией, так и непринимаемые)
- Входные данные должны быть корректными (ожидаемыми после отработки предыущей функции)
- В Input и в Output данные должны быть расписаны с нужной детализацией (важные в этой функции поля)

**Comment by BlackReper086** [comment]
Написан. Требуется проверка.
