### ISSUE TITLE
Получить спецификацию по тегам передаваемым в JSON от почтового сервиса

### ISSUE THREAD

**Issue by TsaplinK** [Students-of-the-city-of-Kostroma/trpo_automation#16]
# Просрочено: 1 день
Получить документацию для интеграции с почтовым сервисом (в частности по паттерну Стратегия)
Срок завершения работ по задаче: 20.03.20
## Epic: #2

**Comment by TsaplinK** [comment]
Обращаться к Коренухину Егору (https://github.com/Sirokko77)

**Comment by nekislev** [comment]
https://docs.google.com/document/d/1wdzsv4y-gV9yEhMEU-ldf8_9o023fY9vsq1xILDyeio/edit

**Comment by None-stopCoding** [comment]
Нужно то, что нам пришлют с почтового сервиса по паттерну Стратегия.
Это устаревший документ и составлялся, когда еще не было понимания, как все должно работать.

**Comment by nekislev** [comment]
https://docs.google.com/document/d/1UWPYAc9Qqtg3XbEyg5CfDk6F5vaSsirt08Jx3DZSYD4/edit
