### ISSUE TITLE
Метод содержит код, делающий невозможным тестирование

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/trpo_automation#162]
Метод search_email в файле APIgoogle содержит строки, предназначенные для файлов конфигурации:

![image](https://user-images.githubusercontent.com/55210615/77089135-7b60fd00-6a16-11ea-86a2-b886ed55ec88.png)

Ожидаемый результат:  в методе будут использоваться переменные, хранящиеся в файле config.py.

**Comment by Svyat935** [comment]
Исправлено.
