### ISSUE TITLE
Метод содержит строку, предназначенную для файла конфигурации

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/trpo_automation#165]
Метод get_service в файле APIgoogle.py содержит строку, предназначенную для файлов конфигурации:

![image](https://user-images.githubusercontent.com/55210615/77102947-b40ad180-6a2a-11ea-9fe9-07e1ba7516d7.png)

Ожидаемый результат: будут использоваться переменные, хранящиеся в файле config.py

**Comment by 0Meridian0** [comment]
проблемы не будет, если есть токен

**Comment by Svyat935** [comment]
Исправлено.
