### ISSUE TITLE
Создать 3 эталонных репозитория 

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#166]
# Срок сдачи: 05.06.20
### Epic: #35
_Пояснения_:
[Ссылка на первый репозиторий](https://github.com/leshastern/strategy1)
[Ссылка на второй репозиторий](https://github.com/leshastern/strategy2)
[Ссылка на третий репозиторий](https://github.com/leshastern/strategy4)

**Comment by leshastern** [comment]
Были созданы три репозитория
[Ссылка на первый репозиторий](https://github.com/leshastern/strategy1)
[Ссылка на второй репозиторий](https://github.com/leshastern/strategy2)
[Ссылка на третий репозиторий](https://github.com/leshastern/strategy4)

**Comment by None-stopCoding** [comment]
Третья ссылка указывает на второй репозиторий (как и вторая)

**Comment by leshastern** [comment]
Исправлено
