### ISSUE TITLE
Написать службу для проекта

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#167]
# Срок сдачи: 13.06.20
### Epic: #35
_Пояснения_: Нужно чтобы наш проект на сервере в 322 аудитории крутился как служба, то есть работал в фоновом режиме, с помощью определенных команд его можно было бы включить или выключить, запускался вместе с системой

**Comment by AlbertShabrov** [comment]
Перезалил обновленную версию нашей программы на сервер в 322 аудиторию. Создал исполняемый файл с командой start-stop-daemon -Svbx путь_до_файла/src. Поставил этот исполняемый файл на автозапуск, Теперь наше приложение является службой и будет запускаться вместе с системой. Для остановки требуется ввести команду start-stop-daemon -Kvx путь_до_файла/src

**Comment by None-stopCoding** [comment]
благодарочка

**Comment by YuriSilenok** [comment]
Где связанный с этой задачей запрос?

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by AlbertShabrov** [comment]
@YuriSilenok Запроса нет, так как задача не привязана к коду. Также все вышеописанное нужно делать на Ubuntu с уже релизной версией в qt.

**Comment by YuriSilenok** [comment]
> Перезалил обновленную версию нашей программы на сервер в 322 аудиторию. Создал исполняемый файл с командой start-stop-daemon -Svbx путь_до_файла/src. Поставил этот исполняемый файл на автозапуск, Теперь наше приложение является службой и будет запускаться вместе с системой. Для остановки требуется ввести команду start-stop-daemon -Kvx путь_до_файла/src

Вы писали что создали файл, почему он не должен быть частью репозитория? Слишком мало информации о том, как этим файлом пользоваться. И что за разновидность исполняемого файла?

**Comment by YuriSilenok** [comment]
> Перезалил обновленную версию нашей программы на сервер в 322 аудиторию. Создал исполняемый файл с командой start-stop-daemon -Svbx путь_до_файла/src. Поставил этот исполняемый файл на автозапуск, Теперь наше приложение является службой и будет запускаться вместе с системой. Для остановки требуется ввести команду start-stop-daemon -Kvx путь_до_файла/src

Вы писали что создали файл, почему он не должен быть частью репозитория? Слишком мало информации о том, как этим файлом пользоваться. И что за разновидность исполняемого файла?

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-167 давно не было активности

**Comment by AlbertShabrov** [comment]
Задача решена, ссылка на реквест [тут](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/pull/288)
