### ISSUE TITLE
Вернуть CI на путь истинный 

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#169]
_Пояснения_: 

- [ ] поставить последнюю версию QT
- [x] проверить работу стадии компиляции
- [ ] настроить deploy стадию для выкатов пре-релизов на dev

**Comment by None-stopCoding** [comment]
1 и 3 пункт?

**Comment by Someone-dono** [comment]
На данный момент CI вновь успешно функционирует. Остальные задачи будут завершены по мере необходимости.

**Comment by YuriSilenok** [comment]
> На данный момент CI вновь успешно функционирует. Остальные задачи будут завершены по мере необходимости.

Нельзя закрывать задачу если работы по ней не завершены или она не потеряла актуальность.
Я не вижу здесь ни первого ни второго случая.

**Comment by Someone-dono** [comment]
Первый пункт было решено оставить в покое. Третий пункт требует совместного решения, посему было решено перенести его на следующий спринт.

**Comment by YuriSilenok** [comment]
Не совсем понятна причина того, почему первый пункт решено оставить в покое, поясните пожалуйста?

Если он перенесен на следующий спринт, то почему тогда закрывалась задача, раз работа над  ним ведется?

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-169 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-169 давно не было активности

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-169 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-169 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-169 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-169 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-169 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-169 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-169 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-169 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-169 давно не было активности

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.
