### ISSUE TITLE
Выявить стилистические  ошибки 

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#170]
# Срок сдачи: 11.06.20
### Epic: #34 
_Пояснения_: пробежаться по всему коду, он должен соответствовать принятым стандартам

**Comment by Someone-dono** [comment]
Ошибки найдены, ответственные за них люди оповещены.

**Comment by YuriSilenok** [comment]
я бы ожидал что будут подняты соответствующие задачи на людей и это было бы оповещение или в рамках этой задачи люди были бы оповещены. И при последнем варианте должна быть ссылка на запрос исправляющий ошибки.

**Comment by Someone-dono** [comment]
Ошибки найдены, ответственные за них люди оповещены.

Список задач, созданных для устранения проблем:
#234 #235 #239 #246

**Comment by YuriSilenok** [comment]
> Ошибки найдены, ответственные за них люди оповещены.
> 
> Список задач, созданных для устранения проблем:
> #234 #235 #239 #246

#235 и #246 - это не задачи, а запросы на слияние.
1. Зачем они здесь?
2. Если вы хотите связать задачу и запрос, то есть соответствующий атрибут, но не умаю что он здесь уместен.
3. Если вы создаете подзадачи, то в их описании нужно указать ссылку на родителя.

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by Someone-dono** [comment]
Ошибки найдены, созданы соответствующие задачи по их устранению:
#234 
#239
