### ISSUE TITLE
Разработать сценарий для функционального тестирования проверки класса-родителя

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#172]
### Epic: #36
_Пояснения_: Разработать сценарии для функционального тестирования метода StrategyLab::checkParentChildrenRelations();

**Comment by MaksimBukhanov** [comment]
Сценарии тестирования метода проверки класса-родителя
[Документ на Google Drive](https://docs.google.com/spreadsheets/d/1d4DwpPxyc5DkmKFavszVM5prBqGhY7CCWIz_CnZOHEs/edit#gid=146939622)

**Comment by None-stopCoding** [comment]
см коммент к задаче https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/issues/173#issuecomment-640069970

**Comment by MaksimBukhanov** [comment]
> см коммент к задаче [#173 (comment)](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/issues/173#issuecomment-640069970)

Посмотрел. Исправил.
[Документ на Google Drive](https://docs.google.com/spreadsheets/d/1d4DwpPxyc5DkmKFavszVM5prBqGhY7CCWIz_CnZOHEs/edit#gid=146939622)

**Comment by None-stopCoding** [comment]
уважуха

**Comment by YuriSilenok** [comment]
почему у вас существуют две папки тестирования и сценарии не сведены в один документ, как вы общую статистику будете настраивать?

**Comment by None-stopCoding** [comment]
@YuriSilenok Насчет общей статистики - откуда, что это, и зачем нужно и к какому времени, слышу впервые) Теперь есть папка Тестирование, основная, и есть папка - автотесты или что-то там - и это папка временная, вспомогательная. Всегда открыты для предложений по части именования временных вспомогательных папок, чтобы не возникало вопросов, подобно Вашему. Эта папка будет удалена, благо проверка структуры папок на гугл диске будет проводиться при сдаче проекта (или не будет?). Насчет сценариев - есть один понятный файл называется - Сценарии тестирования - его название означает, что там лежат сценарии тестирования. Название остальных файлов, которые могут сбить столку так не называются, и тоже будут удалены при сдаче проекта, ибо они вспомогательные. Спасибо!

**Comment by YuriSilenok** [comment]
После демо вопрос еще актуален?

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by MaksimBukhanov** [comment]
> почему у вас существуют две папки тестирования и сценарии не сведены в один документ, как вы общую статистику будете настраивать?

Все сценарии тестирования помещены в один файл, с ним можно ознакомиться [здесь.](https://docs.google.com/spreadsheets/d/1d4DwpPxyc5DkmKFavszVM5prBqGhY7CCWIz_CnZOHEs/edit#gid=146939622)
