### ISSUE TITLE
Разработать сценарий для функционального тестирования проверки класса-детей

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#173]
### Epic: #36 
_Пояснения_: Разработать сценарии для функционального тестирования метода StrategyLab::checkChildren();

**Comment by MaksimBukhanov** [comment]
Сценарии тестирования метода проверок классов-потомков. 
[Документ на Google Drive](https://docs.google.com/spreadsheets/d/1d4DwpPxyc5DkmKFavszVM5prBqGhY7CCWIz_CnZOHEs/edit#gid=146939622)

**Comment by None-stopCoding** [comment]
1. Не заполнены колонки - Предварительные шаги, Шаги - если кейс предназначен только для автотестирования, то напиши там что-то типа "не требуется, обработка автотестом"
2. Не заполнена колонка "Автоматизация" - так автотесты не сработают
3. В колонке тестовые данные есть переносы строк - лучше их убрать, читать потом хреново
4. В колонке Ожидаемый результат - че за messageType? Исходи из того что вернет метод (в данном случае checkCildren()), или можешь спросить у @leshastern как ему удобней будет, автотесты ему писать по этим сценариям
5. Можно пожалуйста больше тест-кейсов, раза в два)))

**Comment by MaksimBukhanov** [comment]
1-4 исправлено. Количество тест-кейсов увеличено.
[Документ на Google Drive](https://docs.google.com/spreadsheets/d/1d4DwpPxyc5DkmKFavszVM5prBqGhY7CCWIz_CnZOHEs/edit#gid=146939622)

**Comment by None-stopCoding** [comment]
отлично!

**Comment by leshastern** [comment]
@None-stopCoding нужно переделать значения ячейек "тестовые данные" по аналогии с кейсами issue-178 (без табуляций, пробелов, перенос строк)

**Comment by None-stopCoding** [comment]
@MaksimBukhanov, тестировщик запрашивает изменения

**Comment by MaksimBukhanov** [comment]
> @None-stopCoding нужно переделать значения ячейек "тестовые данные" по аналогии с кейсами issue-178 (без табуляций, пробелов, перенос строк)

Изменено
[Документ на Google Drive](https://docs.google.com/spreadsheets/d/1d4DwpPxyc5DkmKFavszVM5prBqGhY7CCWIz_CnZOHEs/edit#gid=146939622)

**Comment by YuriSilenok** [comment]
> @MaksimBukhanov, тестировщик запрашивает изменения

вы должны били цитировать тестирощика, что бы было понятно что есть его запрос.

**Comment by YuriSilenok** [comment]
> @MaksimBukhanov, тестировщик запрашивает изменения

вы должны били цитировать тестирощика, что бы было понятно что есть его запрос.

**Comment by leshastern** [comment]
@MaksimBukhanov сообщил что все исправил. Подверждаю. Задача закрыта.

**Comment by YuriSilenok** [comment]
все сценарии и общая статистика должны быть в одном документе

**Comment by None-stopCoding** [comment]
@YuriSilenok Подскажите пожалуйста, что Вас сбило с толку) Общая статистика? Это что-то новенькое)

**Comment by YuriSilenok** [comment]
> @YuriSilenok Подскажите пожалуйста, что Вас сбило с толку) Общая статистика? Это что-то новенькое)

Мы обсудили это на демо?

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by MaksimBukhanov** [comment]
> все сценарии и общая статистика должны быть в одном документе

Все сценарии тестирования были помещены в один файл.
С ним можно ознакомиться [здесь.](https://docs.google.com/spreadsheets/d/1d4DwpPxyc5DkmKFavszVM5prBqGhY7CCWIz_CnZOHEs/edit#gid=146939622)
