### ISSUE TITLE
Реализовать метод LettersConvertToString(letters)

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#175]
Функционал метода:
- Вытаскивает сырые данные из ссылок в поле Body
- При этом конвертирует данные в строковый формат

Что предусмотреть:
- Для каких-то лабораторных (а соответственно и писем) требуется вытаскивать данные, а для каких-то достаточно оставить ссылку. 
Спецификация по JSON [здесь](https://docs.google.com/document/d/1UWPYAc9Qqtg3XbEyg5CfDk6F5vaSsirt08Jx3DZSYD4/edit) 
- Есть два основных типа, в которые происходит конвертация:
- - Текст. (паттерны, ТЗ)
- - XML - документ. (все диаграммы)

Результаты представить в виде модуля на языке python

**Comment by Progoger** [comment]
Доработки системы
Сделал тестовый репозиторий: https://github.com/Progoger/TasksForStudents
Иерархия папок такова:
1)Группа
2)Студенты
3)Лабораторная работа №
4) Все файлы по данной лабораторке
Вроде бы учёл всё, что требовалось

**Comment by Progoger** [comment]
Добавил папку CommonClasses в папку Parsing, так как пока не нашёл, как относительно импортить файлы, так что для относительности пошёл на такие меры

**Comment by urec-programmec** [comment]
Проверим завтра на демке

**Comment by urec-programmec** [comment]
Закрыто, т.к. закрыт pr
