### ISSUE TITLE
Реализовать метод LettersConvertToString(letters).Текст

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#176]
Epic - #175

Реализовать функцию вытаскивания текста программ по ссылкам из репозитория.

Что предусмотреть:
- Работа не с ссылками на конкретные папки, а с ссылкой на репозиторий
- Собирание данных из вложенных папок в репозитории
- Объединение разных файлов в один и merging заголовков, преобразование к совместимому виду.

Результаты представить в виде модулей на языке python

**Comment by Progoger** [comment]
Добавлены поиск файлов в репозитории и во всех папках репозитория
Запись текста файлов в один файл txt

**Comment by urec-programmec** [comment]
Pull request принял
Задача закрывается
