### ISSUE TITLE
Интеграция с клиентом

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#177]
# Срок сдачи: 08.06.20
### Epic: #36 
_Пояснения_:

**Comment by YuriSilenok** [comment]
> Интеграция прошла на ура

дерзкое утверждение, есть ли что-то подтверждающее это?

**Comment by None-stopCoding** [comment]
@YuriSilenok В каком виде вы хотите подтверждения?

**Comment by YuriSilenok** [comment]
отчет о тестировании в ветке dev всех четырех компонентов, лучше что бы это был автоматический отчет из CI.

**Comment by None-stopCoding** [comment]
пока с интегрировались только с командой ИС-а, сегодня планируем с ИС-б
интеграционных тестов пока нет, возможно возьмем на след спринт
