### ISSUE TITLE
Доразработка метода SendJSONForCheck(jsonDates, letters)

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#178]
Разработать метод SendJSONForCheck(jsonDates), отвечающий за отправку JSON на TCP сервер

Что подаётся на вход
Cписок списков вида [[json1, port1], [json2, port2], ..., [jsonn, portn]] 

Что требуется
Отправить каждый json на нужный порт

Результаты представить в виде модуля на языке python

**Comment by urec-programmec** [comment]
Pull request принял
Задача закрывается

**Comment by SkinnerX7** [comment]
Функционал:
    - Отправить письма на проверку в модули проверки писем от ВТ
    - Дождаться проверки каждого из писем
    - Сформировать список экземпляров классов LetterResults по каждому письму, расставить оценки и комментарии от ВТ
    На входе:
    - jsonDates - список с экземплярами json, с нужными данными в нужном формате
    На выходе:
    - None
    Что предусмотреть:
    - Будет синхронный режим работы, когда сначала отправляется первый json потом происходит ожидание ответа на него,
    после чего происходит заполнение нужных полей
    отправить json1 ->
    получить ответ на json1 ->
    Заполнить нужные поля в result1 ->
    отправить json3 ->
    получить ответ на json3 ->
    Заполнить нужные поля в result3 ->
    отправить json3 ->
    получить ответ на json3 ->
    Заполнить нужные поля в result3 ->
    ...
    - Каждый json нужно отправить на нужный порт. Предусмотреть проверку на это в соответствии со спецификацией по JSON
    - Предусмотреть таймаут ожидания, чтобы система не зависала на бесконечное время при ошибках в модулях проверки
    В этом случае заполнять не только поле IsOK но и поле Code

**Comment by SkinnerX7** [comment]
Добавление функционала на спринт 4

**Comment by urec-programmec** [comment]
Закрыто, т.к. задача относится к новой стадии работы
