### ISSUE TITLE
Разработать сценарии для тестирования методов проверки main

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#178]
# Срок сдачи: 09.06.20
### Epic: #36 
_Пояснения_: Сценарии тестирования разработаны, результаты можно посмотреть [здесь](https://docs.google.com/spreadsheets/d/1d4DwpPxyc5DkmKFavszVM5prBqGhY7CCWIz_CnZOHEs/edit?usp=sharing)

**Comment by leshastern** [comment]
Сценарии тестирования разработаны, результаты можно посмотреть [здесь](https://docs.google.com/spreadsheets/d/1d4DwpPxyc5DkmKFavszVM5prBqGhY7CCWIz_CnZOHEs/edit?usp=sharing)

**Comment by leshastern** [comment]
@None-stopCoding check it please and close after

**Comment by None-stopCoding** [comment]
excellent, работа мастера видна

**Comment by YuriSilenok** [comment]
> [ссылка на таблицу](https://docs.google.com/spreadsheets/d/1d4DwpPxyc5DkmKFavszVM5prBqGhY7CCWIz_CnZOHEs/edit?usp=sharing)

это неприемлемое описание ссылки

**Comment by leshastern** [comment]
@YuriSilenok пожалуйста, проверьте новое описание ссылки

**Comment by YuriSilenok** [comment]
> @YuriSilenok пожалуйста, проверьте новое описание ссылки

я бы сказал что нужно написать имя документа, дать какое-то описание.
Приоритет в том, что бы дать понять что эта за ссылка, не все ссылки в задачах прямо связаны с темой задачи.
Например
Сценарии тестирования разработаны, результаты можно посмотреть [здесь](https://docs.google.com/spreadsheets/d/1d4DwpPxyc5DkmKFavszVM5prBqGhY7CCWIz_CnZOHEs/edit?usp=sharing)
