### ISSUE TITLE
Разработать сценарии для тестирования методов проверки по конфигу

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#179]
# Срок сдачи: 09.06.20
### Epic: #36 
_Пояснения_: [документ на Google Drive](https://docs.google.com/spreadsheets/d/1d4DwpPxyc5DkmKFavszVM5prBqGhY7CCWIz_CnZOHEs/edit?usp=sharing)

**Comment by leshastern** [comment]
[документ на Google Drive](https://docs.google.com/spreadsheets/d/1d4DwpPxyc5DkmKFavszVM5prBqGhY7CCWIz_CnZOHEs/edit?usp=sharing)

@None-stopCoding please check it

**Comment by None-stopCoding** [comment]
Норм

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by AnastasiVokhmyanina28** [comment]
Веха добавлена

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by AnastasiVokhmyanina28** [comment]
метка добавлена
