### ISSUE TITLE
Проверка письма на соответствие структуре и его валидация

### ISSUE THREAD

**Issue by cyberAndrey** [Students-of-the-city-of-Kostroma/trpo_automation#18]
Получаю тему и телу письма
Проверяю на соответствие [шаблону](https://docs.google.com/document/d/1DRhgepxVwoscylIS2LCW-po5SFBdqOr-oo92bP_XfHE/edit) 
Отправляю json с данными для проверки и записи в таблицу

**Comment by cyberAndrey** [comment]
Задание выполнил

**Comment by urec-programmec** [comment]
Ожидаю результатов по задаче в любом виде для проверки

**Comment by YuriSilenok** [comment]
укажите причину закрытия задачи

**Comment by urec-programmec** [comment]
Задача не соответствует спецификации. Закрыто за нерелевантностью.
