### ISSUE TITLE
Исправить таблицу сценариев тестирования

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#180]
# Срок сдачи: 09.06.20
### Epic: #36 
_Пояснения_: [Ссылка на документ](https://docs.google.com/spreadsheets/d/1d4DwpPxyc5DkmKFavszVM5prBqGhY7CCWIz_CnZOHEs/edit?usp=sharing)

**Comment by leshastern** [comment]
Таблица исправлена. [Ссылка](https://docs.google.com/spreadsheets/d/1d4DwpPxyc5DkmKFavszVM5prBqGhY7CCWIz_CnZOHEs/edit?usp=sharing)
