### ISSUE TITLE
Подготовить макет презентации проекта

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#182]
# Срок сдачи: 09.06.20
### Epic: #37 
_Прогресс по задаче_: https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/issues/182#issuecomment-641734426

**Comment by None-stopCoding** [comment]
Составил план презентации - [макет](https://docs.google.com/presentation/d/1qX9rwCLWF8VJELB2jDAePrIChDISP2yozEtlo6k91aE/edit?usp=sharing), обсудим на паре

**Comment by YuriSilenok** [comment]
> Составил план презентации - [макет](https://docs.google.com/presentation/d/1qX9rwCLWF8VJELB2jDAePrIChDISP2yozEtlo6k91aE/edit?usp=sharing), обсудим на паре

Задача ставилась таким образом, что на паре вы показываете готовую презентацию, которую мы обсуждаем, требования к содержанию были выданы в процессе спринта.

**Comment by None-stopCoding** [comment]
@YuriSilenok Будьте добры ссылку на требования содержания. Про готовую презентацию слышу впервые)

**Comment by YuriSilenok** [comment]
Об этом упоминалось в общем чате,
зафиксировал требования в виде задачи #250

**Comment by None-stopCoding** [comment]
Если это упоминалось в общем чате, то рад сообщить, что составленный план полностью соответствует перечисленным там требованиям. Спасибо
