### ISSUE TITLE
Написать общие автотесты для протокола

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#183]
# Срок сдачи: 09.06.20
### Epic: #36 
_Обратить внимание_: https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/issues/183#issuecomment-639733286

**Comment by YuriSilenok** [comment]
Я не вижу здесь никаких отчетов о выполненной работе.

**Comment by YuriSilenok** [comment]
> Теперь для того чтобы написать автотест достаточно добавить строчку в гугл таблице Сценарии

Если вы говорите о сценариях, то нужно прикреплять ссылку, я не могу понять что за строчку нужно добавить, какой задачей это вообще регламентировано, где взять описание как этим пользоваться и какие требования к самой строке?

**Comment by None-stopCoding** [comment]
@YuriSilenok  Была новость в нашей беседе ВК, дублирую сюда

НОВОСТЬ
У нас на гугл диске есть файл [Сценарии тестирования](https://docs.google.com/spreadsheets/d/1d4DwpPxyc5DkmKFavszVM5prBqGhY7CCWIz_CnZOHEs/edit?usp=sharing)

Этой задачей я вот что сделал:

Теперь для того чтобы написать автотест достаточно добавить строчку в гугл таблице Сценарии тестирования. Если есть желание прогнать тесты локально, то сначала нужно запустить скрипт для формирования тестовых кейсов из гугл таблицы.

Команда: trpo_automation/LR/07/tests/getTestSuites/dowloadTestSuites.sh

CI должен будет запускать этот скрипт в процессе работы

Очень важно чтобы тестовые данные и ожидаемый результат писались верно, до запятой, иначе тесты не пройдут!

Не забываем указывать правильное значение параметра "Автоматизация" в таблице, в зависимости от него, система понимает, это ручной или авто тест

**Comment by YuriSilenok** [comment]
> @YuriSilenok Была новость в нашей беседе ВК, дублирую сюда
> 
> НОВОСТЬ
> У нас на гугл диске есть файл [Сценарии тестирования](https://docs.google.com/spreadsheets/d/1d4DwpPxyc5DkmKFavszVM5prBqGhY7CCWIz_CnZOHEs/edit?usp=sharing)
> 
> Этой задачей я вот что сделал:
> 
> Теперь для того чтобы написать автотест достаточно добавить строчку в гугл таблице Сценарии тестирования. Если есть желание прогнать тесты локально, то сначала нужно запустить скрипт для формирования тестовых кейсов из гугл таблицы.
> 
> Команда: trpo_automation/LR/07/tests/getTestSuites/dowloadTestSuites.sh
> 
> CI должен будет запускать этот скрипт в процессе работы
> 
> Очень важно чтобы тестовые данные и ожидаемый результат писались верно, до запятой, иначе тесты не пройдут!
> 
> Не забываем указывать правильное значение параметра "Автоматизация" в таблице, в зависимости от него, система понимает, это ручной или авто тест

гитхаб является первоочередным источником. из него должна дублироваться информация куда угодно.

вы хотите сказать что код тестов не на гитхабе, а в гугл таблице и парсится таблица, а статусы в таблицу проставляются?

**Comment by None-stopCoding** [comment]
сам код для автотестирования присутствует, но его суть заключается в том, чтобы пробежаться по тестовым данным, которые лежат в файле. Файл формируется скриптом из гугл таблицы.

**Comment by YuriSilenok** [comment]
а статусы о выполнении теста проставляются в документ? 
Это было бы логичным завершением использования этой таблицы.

**Comment by None-stopCoding** [comment]
как вариант, можно реализовать в перспективе. Проблема возникнет в том, что данные из гугл таблицы загружаются отдельным скриптом написанным на питоне, из qt я никак не касаюсь гугл таблицы.

**Comment by None-stopCoding** [comment]
по сути идея идеальна

**Comment by YuriSilenok** [comment]
понятно. нужно подумать над скриптом, опять же на питоне, который бы выгрузил результаты обратно. Думаю qt мог бы сохранить некоторый отчет, а питоновский скрипт выгрузил бы отчет обратно. Думаю стоит поднять на это карточку.

**Comment by None-stopCoding** [comment]
это не проблема, вопрос как стриггерить питоновский скрипт

**Comment by None-stopCoding** [comment]
хотя, если в CI записать, то должно сработать

**Comment by None-stopCoding** [comment]
но это на ближайшее будущее - сейчас пре-релиз)

**Comment by YuriSilenok** [comment]
> но это на ближайшее будущее - сейчас пре-релиз)

я и говорю, можно сделать карточку или задачу что бы не забыть об этом.
