### ISSUE TITLE
Возродить документацию

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#185]
# Срок сдачи: 09.06.20
### Epic: #37 
_Пояснения_:  конкретно пункты, по которым документация воскрешена
[Восстановленная документация](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/wiki)

**Comment by ghost** [comment]
[Восстановленная документация](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/wiki)

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by AnastasiVokhmyanina28** [comment]
Веха добавлена
