### ISSUE TITLE
Шаблон писем для бесконечного ожидания ответа от модулей проверок

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#186]
В системе появилось новое состояние письма. Оно связано с бесконечным (больше установленного таймаута) ожиданием ответа от модулей проверки ЛР.

Нужно
- Сформировать шаблон ответного письма

Предусмотреть
- Код для этого состояния уже назначен. Документация [здесь](https://docs.google.com/spreadsheets/d/1o6pLF4PXGc6h6X7q4epYjuzTCzZmDobuR0on4av4wO4/edit#gid=1847888026)

Результат - дополненная документация

**Comment by BlackReper086** [comment]
Документ исправлен. Добавление шаблона не требуется.

**Comment by urec-programmec** [comment]
Задача принята
