### ISSUE TITLE
Шаблон для в письме есть вложение

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#187]
В системе появилось новое состояние письма. Оно связано тем, что если в письме есть вложения, для системы это ошибочное состояние

Нужно
- Сформировать шаблон ответного письма

Предусмотреть
- Код для этого состояния уже назначен. Документация [здесь](https://docs.google.com/spreadsheets/d/1o6pLF4PXGc6h6X7q4epYjuzTCzZmDobuR0on4av4wO4/edit#gid=1847888026)

Результат - дополненная документация

**Comment by BlackReper086** [comment]
Добавил шаблон при отсутствии ссылок. Изменен шаблон при отсутствии вложений на при наличии вложений.

**Comment by urec-programmec** [comment]
Задача принята
