### ISSUE TITLE
Разобраться с файлом "Функциональное тестирование сервера" на гугл диске

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#190]
# Срок сдачи: 09.06.20
### Epic: #37 
_Пояснения_: Если не нужен - удалить, если нужен, комментом написать - для каких целей.

**Comment by leshastern** [comment]
Файл был удален, так как является устаревшим, вместо него теперь есть [красивая таблица сценариев](https://docs.google.com/spreadsheets/d/1d4DwpPxyc5DkmKFavszVM5prBqGhY7CCWIz_CnZOHEs/edit?usp=sharing)
