### ISSUE TITLE
Написать отчет о тестировании по выпуску пре-релиза

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#191]
# Срок сдачи: 09.06.20
### Epic: #36  
_Прогресс по задаче_:

- Добавлена информация о прохождении тестов в таблицу [Сценариев тестирования](https://docs.google.com/spreadsheets/d/1d4DwpPxyc5DkmKFavszVM5prBqGhY7CCWIz_CnZOHEs/edit?usp=sharing)

**Comment by None-stopCoding** [comment]
см 'Прогресс по задаче' в описании к задаче

**Comment by YuriSilenok** [comment]
отче о тестировании должен быть в том же документе что и сценарии тестирования

**Comment by None-stopCoding** [comment]
@YuriSilenok В сценариях тестирования имеется графа-индикатор проходимости тестов.
Вы подразумеваете вклинить таблицу с отчетом под таблицей Сценарии тестирования?

**Comment by YuriSilenok** [comment]
Я имею ввиду что в документе со сценариями должен быть лист, отчет о тестировании.
нам незачем плодить несколько документов, если данные между собой очень связаны, и да, цифры в отчете должны формироваться при помощи формул, то есть автоматически.

**Comment by None-stopCoding** [comment]
ага, насчет листа понял, насчет автоматизации в планах на следующий спринт сделать выгрузку данных о прохождении тестов через CI, о чем вы говорили

**Comment by None-stopCoding** [comment]
Добавил лист Отчет v.0.0.0.10 в таблицу [Сценарии тестирования](https://docs.google.com/spreadsheets/d/1d4DwpPxyc5DkmKFavszVM5prBqGhY7CCWIz_CnZOHEs/edit?usp=sharing)
