### ISSUE TITLE
Шаблон для вариант не соответствует необходимым

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#191]
В системе появилось новое состояние письма. Оно связано тем, что если вариант больше 15 или меньше 1 или вообще не число, для системы это ошибочное состояние

Нужно
- Сформировать шаблон ответного письма

Предусмотреть
- Код для этого состояния уже назначен. Документация [здесь](https://docs.google.com/spreadsheets/d/1o6pLF4PXGc6h6X7q4epYjuzTCzZmDobuR0on4av4wO4/edit#gid=1847888026)

Результат - дополненная документация

**Comment by BlackReper086** [comment]
Шаблон написан.

**Comment by urec-programmec** [comment]
Задача принята
