### ISSUE TITLE
Рефакторинг unittest'ов

### ISSUE THREAD

**Issue by SkinnerX7** [Students-of-the-city-of-Kostroma/trpo_automation#196]
- рефакторинг unittest'ов 
- небольшое изменение функции SendJSONForCheck, чтение конфига

**Comment by SkinnerX7** [comment]
Был принят pr, задача закрывается

**Comment by YuriSilenok** [comment]
Добрый день. Вы не удалили ветку issue-196 и закрыли задачу

**Comment by SkinnerX7** [comment]
Ветка была удалена

**Comment by YuriSilenok** [comment]
Добрый день. Вы не удалили ветку issue-196 и закрыли задачу

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-196 давно не было активности

**Comment by SkinnerX7** [comment]
Ветка удалена
