### ISSUE TITLE
Тестирование ветки с логированием

### ISSUE THREAD

**Issue by SkinnerX7** [Students-of-the-city-of-Kostroma/trpo_automation#197]
Что необходимо:
- Протестировать ветку с логированием, указать на ошибки

**Comment by YuriSilenok** [comment]
Где результаты тестирования?

**Comment by SkinnerX7** [comment]
Результаты тестирования объединены
Находятся в задаче #154

**Comment by YuriSilenok** [comment]
Причём тут тестирование 8 билда и тестирование в этой ветке, вы вообще о чем?

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by urec-programmec** [comment]
Задача закрывается, т.к. была реализована
