### ISSUE TITLE
Логирование уровнем Error

### ISSUE THREAD

**Issue by cyberAndrey** [Students-of-the-city-of-Kostroma/trpo_automation#198]
Реализовать логирование уровня ERROR по [этим](https://docs.google.com/spreadsheets/d/1_0wGJbMO4SctmNRMTFkDYaOhgvOVKfpT8hklMQCNxEg/edit#gid=0) правилам

**Comment by cyberAndrey** [comment]
Реализация есть. Код в ветке 157, так как она еще не замержена в основную ветку, а уровень error - добавление к функционалу 157 ветки
Перехожу к этапу тестирования логов для всех(по возможности) функций проекта

**Comment by YuriSilenok** [comment]
> Реализовать логирование уровня ERROR по [этим](docs.google.com/spreadsheets/d/1_0wGJbMO4SctmNRMTFkDYaOhgvOVKfpT8hklMQCNxEg/edit#gid=0) правилам

ссылка не действительная, ошибка 404

**Comment by YuriSilenok** [comment]
> Реализация есть. Код в ветке 157, так как она еще не замержена в основную ветку, а уровень error - добавление к функционалу 157 ветки
> Перехожу к этапу тестирования логов для всех(по возможности) функций проекта

где запрос на слияние ?
я не понимаю второй части Вашего комментария, поясните подробнее.

**Comment by cyberAndrey** [comment]
> > Реализовать логирование уровня ERROR по [этим](docs.google.com/spreadsheets/d/1_0wGJbMO4SctmNRMTFkDYaOhgvOVKfpT8hklMQCNxEg/edit#gid=0) правилам
> 
> ссылка не действительная, ошибка 404

Исправил ссылку
Запрос на слияние не делал так как из-за возможных ошибок может не работать проект. Протестирую локально и сделаю pr

**Comment by YuriSilenok** [comment]
> Запрос на слияние не делал так как из-за возможных ошибок может не работать проект.

Если запрос существует, то на него должна быть ссылка.
![image](https://user-images.githubusercontent.com/14871471/84125014-a3279600-aa44-11ea-90bc-81b57b89e351.png)
Для предварительного тестирования на сервера CI вы можете сделать черновик запроса.

**Comment by cyberAndrey** [comment]
#157 - основная. Выполнено

**Comment by YuriSilenok** [comment]
Я не увидел ссылки на запрос, где она?

**Comment by cyberAndrey** [comment]
Выполнено
