### ISSUE TITLE
Дополнить пул задач для паттерна Стратегия

### ISSUE THREAD

**Issue by TsaplinK** [Students-of-the-city-of-Kostroma/trpo_automation#20]
Дополнить пул задач для паттерна Стратегия и уточнить формулировки

**Comment by YuriSilenok** [comment]
кто делает эту задачу?

**Comment by AnastasiVokhmyanina28** [comment]
ссылка на документ с задачами: https://docs.google.com/document/d/1QJxrZKpf69n_SEcLJ-Ni6uKhueuDTLZHdZCGMwyDBZ8/edit
