### ISSUE TITLE
Ошибка в регистре

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/trpo_automation#203]
Ошибка в регистре в методе отправления письма студенту:

![image](https://user-images.githubusercontent.com/55210615/77659958-c84e5180-6f89-11ea-9135-8b3ae154f4da.png)

Ожидаемый результат: Subject с заглавной буквы.

**Comment by 0Meridian0** [comment]
ошибка была исправлена в [ветке 171](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/tree/issue-171)

**Comment by MoL4okkk** [comment]
Исправлено
