### ISSUE TITLE
Разработать сценарий тестирования модуля Server

### ISSUE THREAD

**Issue by vvtatyana** [Students-of-the-city-of-Kostroma/trpo_automation#204]
Написать сценарий тестирования и отчет о тестировании модуля Server в формате Google таблиц
[Тестирование модуля Server](https://docs.google.com/spreadsheets/d/173fcVRsMoGgEgocefV-_fLICh7-Jk9ukjcRUyW3-4ec/edit#gid=66827693)
[Отчет о тестировании](https://docs.google.com/spreadsheets/d/173fcVRsMoGgEgocefV-_fLICh7-Jk9ukjcRUyW3-4ec/edit#gid=392630057)

**Comment by YuriSilenok** [comment]
> "Создание подключения Передача JSON-строки"

При тестировании протокола передачи данных, вы тестируете Определенные сообщения.
Из вашего отчета мне непонятно будет, какие из сообщений протестированы и имеют проблемы.

**Comment by avilova** [comment]
Проверено

**Comment by YuriSilenok** [comment]
и все же я не смог понять из этого отчета, есть ли у вас тесты проверяющие ответ сервера реджектами?
![image](https://user-images.githubusercontent.com/14871471/84247847-4940d200-ab11-11ea-8b79-96b439e8ebc7.png)

**Comment by avilova** [comment]
ошибка исправлена

**Comment by YuriSilenok** [comment]
![image](https://user-images.githubusercontent.com/14871471/84256575-c4f44c00-ab1c-11ea-80e4-5c6b9ed4fd7d.png)
Вы меня извините конечно, но вот есть лист `Протокола передачи данных`, я в ней вижу всего 16 тестов, а у вас 15+15. Почему так?
Пожалуйста, сделайте так, что бы цифры который вы получаете в итоговой таблице, формировались автоматически.
И еще, вот у нас спека на протокол.
Ваш сервер может принять один тип сообщений
- Запрос на проверку лабораторной работы

ответить тремя типами сообщений.
- Сообщения о результатах проверки лабораторной работы
- Сообщение о неверном формате запроса на сервер
- Сообщение о внутренней ошибке сервера
 
Я хочу понять, что из этого вы протестировали?
