### ISSUE TITLE
Написать шаблон для решения лабароторной работы по паттерну Стратегия

### ISSUE THREAD

**Issue by TsaplinK** [Students-of-the-city-of-Kostroma/trpo_automation#21]
Срок завершения работ по задаче: конец спринта
Epic: #2

**Comment by YuriSilenok** [comment]
Кто делает эту задачу?

**Comment by None-stopCoding** [comment]
Текущий прогресс по задаче:
1. @SlenderWoker решает все 15 задачек по паттерну Стратегия (разные реализации)
2. @None-stopCoding создает набор проверок (шаблон) для программного кода лабы

**Comment by None-stopCoding** [comment]
[Шаблон собственной персоной](https://docs.google.com/document/d/1VMtT235kwXve-s164ntW3EsJjV1_KUOcKixMAYj8iUM/edit?usp=sharing)
