### ISSUE TITLE
Описать и реализовать процесс валидации письма

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#22]
Водопад фильтров с чётким приоритетом
На вход подаются тестовые письма, сформированные командой тестирования, разделённые по разным категориям
[Ссылка](https://docs.google.com/document/d/1knlDwZ4lGp7NlXlYRQp_11sQAKZlG4qBdP2qyhC0TQY/edit) на письма

После проверки писем каждому письму назначается код. Ссылка на соответствие состояний и кодов [здесь](https://docs.google.com/document/d/12mSzNBvU_WRPhW6snqCZLgmx2ziJRMnahdztMTvb8wk/edit#heading=h.gjdgxs)

Результаты
- Реализация — класс на языке python, отвечающий за реализацию данного функционала
- Документация 
- - Пояснительная записка, в которой будет прописан цикл алгоритма проверки
- - Либо диаграмма вызовов

**Comment by urec-programmec** [comment]
Ожидаю комментариев о проделанной работе

**Comment by cyberAndrey** [comment]
задание выполнил
Код в issue-18
Описание алгоритма [здесь](https://docs.google.com/document/d/15Q_UAAx9t5kV54nmH6MoFaj9ALFjcynmVDsKJy6U6uY/edit)
Пока без кодов писем

**Comment by urec-programmec** [comment]
Задача принимается
Жду pull request в ветку Google

**Comment by urec-programmec** [comment]
https://www.draw.io/#G1uBk9EZCwKGp3pa4MURUgB9tz5a2x9DN_

**Comment by urec-programmec** [comment]
Pull request принял
Задачу закрываю
