### ISSUE TITLE
Исследовать возможность построения отчетов в QT Creator

### ISSUE THREAD

**Issue by None-stopCoding** [Students-of-the-city-of-Kostroma/trpo_automation#220]
# Срок сдачи: 01.04.20
### Epic: #209
_Пояснения_: построение отчетов по покрытию кода Unit тестами (и предложить сервис/ПО с помощью которого можно это будет сделать, если в QT Creator нельзя)

**Comment by leshastern** [comment]
Отчет об исследовании [здесь](https://docs.google.com/document/d/1xu_zbK7XQC9KfASiw0AqTOToW1cOOYQLF6LRceMvMkI/edit?usp=sharing).
