### ISSUE TITLE
Подготовка релиза к демке

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#223]
- [x] Слить все изменения
- [x] Протестировать ветку Андрея

**Comment by YuriSilenok** [comment]
Вы смотрели что у Вас с [отчетом](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/pull/236#issuecomment-640843080)?

**Comment by YuriSilenok** [comment]
> * Слить все изменения
> * Протестировать ветку Андрея


возможно стоит использовать чекбоксы, что бы понимать, какие из этих задач выполнены, а какие нет.

```
- [ ] 1111
- [x] 2222
```

**Comment by YuriSilenok** [comment]
Какие есть обновления по этой задаче?

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by urec-programmec** [comment]
Задача закрывается, т.к. была реализована
