### ISSUE TITLE
Интеграция проектов

### ISSUE THREAD

**Issue by CatherinePRO** [Students-of-the-city-of-Kostroma/trpo_automation#224]
Интеграция проектов групп 18-ИСбо-2б и ВТ. Развертывание на удаленном сервере.

**Comment by CatherinePRO** [comment]
Приложения развернуты на удаленном сервере

**Comment by CatherinePRO** [comment]
Интеграция с ЛР 03
Результат: подключение к серверу происходит, но сервер начинает проверку работы уже после закрытия соединения сервером запроса, соответственно ответа нет 
P.S. - проверка работы осуществляется приблизительно в течение двух минут

**Comment by CatherinePRO** [comment]
Интеграция с ЛР 07
Результат: удалось добиться отправки ЛР на проверку и получения ответа (почти мгновенно), но файл main2... сервера запроса не соответствует спецификации JSON, поэтому необходимо исправить на сервере запроса:
1) метод читающий репозиторий - необходимо возвращать не html, а массив строчек, где каждая строчка класс с методом (можно этого не делать, т.к. этот функционал реализован на сервере проверки и от вас ожидают получить либо ссылку на репозиторий, либо соответствующую структуру)
2) исходя из того, что будет решено с пунктом 1 - сформировать JSON по спецификации. Или вы используете при отправке только "link", или только "code". При выходе из метода, обработки ссылок/репозитория есть случай возвращения код статуса - "08". Данный случай не обрабатывается при формировании JSON
3) Пересмотреть метод подключения к серверу проверки! Одной из ошибок является присвоение комментария, который не возвращается сервером ответа, т.к. ЛР проверена и оценка положительная (вылетает в эксепшн)

**Comment by CatherinePRO** [comment]
На текущий момент можно отправить на почту эталонное письмо с ЛР07 и посмотреть взаимодействие с сервером проверки, процесс выставления оценки в журнал, ответное письмо пользователю.

**Comment by None-stopCoding** [comment]
Рады слышать хорошие новости!

**Comment by YuriSilenok** [comment]
> Интеграция с ЛР 07
> Результат: удалось добиться отправки ЛР на проверку и получения ответа (почти мгновенно), но файл main2... сервера запроса не соответствует спецификации JSON, поэтому необходимо исправить на сервере запроса:
> 
> 1. метод читающий репозиторий - необходимо возвращать не html, а массив строчек, где каждая строчка класс с методом (можно этого не делать, т.к. этот функционал реализован на сервере проверки и от вас ожидают получить либо ссылку на репозиторий, либо соответствующую структуру)
> 2. исходя из того, что будет решено с пунктом 1 - сформировать JSON по спецификации. Или вы используете при отправке только "link", или только "code". При выходе из метода, обработки ссылок/репозитория есть случай возвращения код статуса - "08". Данный случай не обрабатывается при формировании JSON
> 3. Пересмотреть метод подключения к серверу проверки! Одной из ошибок является присвоение комментария, который не возвращается сервером ответа, т.к. ЛР проверена и оценка положительная (вылетает в эксепшн)

Не забудьте поднять баги

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-224 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-224 давно не было активности

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Требуются уточнения обстоятельств закрытия задачи.
Заголовок и метки предполагают наличие запроса на слияние или связанных задач.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.
