### ISSUE TITLE
Добавление интеграционных тестов

### ISSUE THREAD

**Issue by DanilKozlov00** [Students-of-the-city-of-Kostroma/trpo_automation#225]
Добавить интеграционные тесты для проверки совместной работоспособности классов Selenium+Server

**Comment by YuriSilenok** [comment]
Кажется ваш [отчет](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/pull/227#issuecomment-640581074) не работает

**Comment by avilova** [comment]
проверено

**Comment by YuriSilenok** [comment]
> проверено

и какой результат?

**Comment by DanilKozlov00** [comment]
Duplicate of [226](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/issues/226#issuecomment-645549782)
