### ISSUE TITLE
Добавить логирование в файл

### ISSUE THREAD

**Issue by DanilKozlov00** [Students-of-the-city-of-Kostroma/trpo_automation#226]
Добавить логирование в файл вида .txt

**Comment by YuriSilenok** [comment]
Кажется ваш [отчет](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/pull/228#issuecomment-640580759) не работает

**Comment by DanilKozlov00** [comment]
> Кажется ваш [отчет](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/pull/228#issuecomment-640580759) не работает

Кажется проблема в том что он не может дать отчет после удаления ветки 
На данный момент, если посмотреть [все merge pull](https://codecov.io/gh/Students-of-the-city-of-Kostroma/trpo_automation/pulls?state=merged&_pjax=%23pjax-outer), то у каждого из них не находит отчета, однако [самый последний,](https://codecov.io/gh/Students-of-the-city-of-Kostroma/trpo_automation/pull/241/tree) у которого ветка еще не удалена спокойно просматривается

**Comment by avilova** [comment]
проверено

**Comment by YuriSilenok** [comment]
> > Кажется ваш [отчет](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/pull/228#issuecomment-640580759) не работает
> 
> Кажется проблема в том что он не может дать отчет после удаления ветки
> На данный момент, если посмотреть [все merge pull](https://codecov.io/gh/Students-of-the-city-of-Kostroma/trpo_automation/pulls?state=merged&_pjax=%23pjax-outer), то у каждого из них не находит отчета, однако [самый последний,](https://codecov.io/gh/Students-of-the-city-of-Kostroma/trpo_automation/pull/241/tree) у которого ветка еще не удалена спокойно просматривается

1. Выяснить, как правильно удалять ветки, нужно ли какое-то время держать ветку не удаленной, пока сформируется сам отчет.

2. судя по всему ваша ссылка на `самый последний` ведет на какой-то отчет и исходя из урл, это запрос #241, но я в нем не вижу никаких ссылок на отчет который вы предоставили

**Comment by DanilKozlov00** [comment]
Вроде исправил генерацию отчетов, в #276 все работает
