### ISSUE TITLE
Написать документацию по формату передачи данных

### ISSUE THREAD

**Issue by None-stopCoding** [Students-of-the-city-of-Kostroma/trpo_automation#226]
# Срок сдачи: 25.04.20
### Epic: #211 
_Пояснения_: передача данных между нашим и почтовым сервисом
[Документация](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/wiki/Общение-сервера-с-клиентом)

**Comment by Sergey-student** [comment]
[1](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/wiki/Документация-по-структуре-папок-в-системе)

**Comment by Sergey-student** [comment]
[Общение сервера с клиентом](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/wiki/Общение-сервера-с-клиентом)
