### ISSUE TITLE
Написать документацию (сервер, проверка лаб)

### ISSUE THREAD

**Issue by None-stopCoding** [Students-of-the-city-of-Kostroma/trpo_automation#227]
# Срок сдачи: 24.04.20
### Epic: #211 
_Пояснения_: документация по формату общения сервера с классом проверки лаб по паттерну Стратегия
[Документация](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/wiki/Общение-сервера-с-классом-проверки-лаб-по-паттерну-Стратегия)

**Comment by None-stopCoding** [comment]
прогресс по задаче?

**Comment by Sergey-student** [comment]
[Ссылка на документацию по задаче](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/wiki)

**Comment by Sergey-student** [comment]
[Документация по общению сервера с классом проверки лабораторных работ по паттерну Стратегия](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/wiki/Общение-сервера-с-классом-проверки-лаб-по-паттерну-Стратегия)
