### ISSUE TITLE
Написать документацию (проверка лаб, github)

### ISSUE THREAD

**Issue by None-stopCoding** [Students-of-the-city-of-Kostroma/trpo_automation#228]
# Срок сдачи: 27.04.20
### Epic: #211
_Пояснения_: документация по формату общения класса проверки лаб по паттерну Стратегия с классом получения данных с гитхаба

 Задача не соответствует дейсвительности, общения класса проверки лаб с тем классом, что получает листинг, не существует, заместо этого сделана документация по общению сервером с классом получения листинга с гитхаба. [Документация](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/wiki/Общение-сервера-с-сервисом-получения-листинга)

**Comment by Sergey-student** [comment]
[Общение сервера с сервисом получения листинга кода](Общение сервера с сервисом получения листинга)
