### ISSUE TITLE
Написать документацию по структуре системы

### ISSUE THREAD

**Issue by None-stopCoding** [Students-of-the-city-of-Kostroma/trpo_automation#229]
# Срок сдачи: 28.04.20
### Epic: #211
_Пояснения_: документация по структуре папок в нашей системе (где что хранится)
[Документация](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/wiki/Файловая-структура)

**Comment by Sergey-student** [comment]
[Файловая структура](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/wiki/Файловая-структура)
