### ISSUE TITLE
Работа с общим конфигом лабораторных 

### ISSUE THREAD

**Issue by SkinnerX7** [Students-of-the-city-of-Kostroma/trpo_automation#229]
Считывать общий конфиг лабораторных работ

**Comment by SkinnerX7** [comment]
Был принят pr, задача закрывается

**Comment by YuriSilenok** [comment]
Добрый день. Вы не удалили ветку issue-229 и закрыли задачу

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-229 давно не было активности

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by urec-programmec** [comment]
Задача закрывается, т.к. была реализована

**Comment by YuriSilenok** [comment]
Добрый день. Вы не удалили ветку issue-229 и закрыли задачу

**Comment by SkinnerX7** [comment]
Ветка удалена
