### ISSUE TITLE
Изучить работу с Google Таблицы

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#23]
Критерии изучения
- получить программно данные из таблицы в рамках своей учётной записи
- записать программно данные в таблицу в рамках своей учётной записи
- получить программно данные из таблицы в рамках чужой учётной записи
- записать программно данные в таблицу в рамках чужой учётной записи

Результаты представить в виде класса или набора функций

**Comment by CatherinePRO** [comment]
Выполнена настройка сервисного аккаунта

**Comment by CatherinePRO** [comment]
Реализовано чтение и запись данных

**Comment by CatherinePRO** [comment]
Выборка данных в процессе

**Comment by urec-programmec** [comment]
Принял.
Проверил pull request ы
