### ISSUE TITLE
Реализовать метод дешифровки

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/trpo_automation#234]
Реализовать метод, дешифрующий файлы конфигурации

**Comment by MoL4okkk** [comment]
Реализованы методы, дешифрующие ранее зашифрованные .json файлы и ID используемых таблиц.
Метод дешифровки токенов не реализован, так как возникают проблемы при обращении к параметрам объекта Credentials.

**Comment by Svyat935** [comment]
Задача выполнена, проблемы дешифровки переходят в баг.
