### ISSUE TITLE
 Пофиксить баг с проверкой на метод вызова выполнения стратегии

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#238]
### Epic: #35 
_Пояснения_: Если отсутствует метод выполнения стратегии (executeStrategy), то вывод ошибки должен быть таким: "There is no function call on the context class object", а выводится это: "The execute function is called more than once".

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-238 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-238 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-238 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-238 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-238 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-238 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-238 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-238 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-238 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-238 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-238 давно не было активности

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.
