### ISSUE TITLE
Изучить работу с Gmail

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#24]
Критерии изучения

- отправить программно письмо на чужой почтовый ящик
- получить данные о письме и пользователе из последнего отправленного письма
- получить данные о письме и пользователе из набора  последних отправленных писем

Результаты представить в виде класса или набора функций

**Comment by urec-programmec** [comment]
Ожидаю комментариев о проделанной работе

**Comment by VladmirV** [comment]
Создана ветка issue-24

**Comment by VladmirV** [comment]
Добавлены первичные данные.

**Comment by VladmirV** [comment]
Реализованы функция для авторизации.

**Comment by VladmirV** [comment]
Реализована функция, которая отправляет сообщения. На вход поступает SMTP объект, адрес получателя, заголовок, текст.

**Comment by VladmirV** [comment]
Процесс реализована функция прочтения сообщения. На вход поступает IMAP объект.

**Comment by VladmirV** [comment]
Реализована возможность получения имени и адреса отправителя.

**Comment by VladmirV** [comment]
Реализована возможность получения темы сообщения.

**Comment by VladmirV** [comment]
Реализована возможность получения вложений из прочитанного письма.

**Comment by VladmirV** [comment]
Трудности с получением body. Необходимо дополнительное время для доработки.

**Comment by VladmirV** [comment]
Задача выполнена.

**Comment by urec-programmec** [comment]
Принял pull request 
Задачу закрываю
