### ISSUE TITLE
Построение отчета по открытию модульными тестами.

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#241]
# Срок сдачи: 24.04.20
Epic: #209 
_Пояснения_: добавить ссылку на задачу с непрерывной интеграцией,

**Comment by leshastern** [comment]
На текущий момент задача реализована на 75%, созданы все необходимые файлы [(выложены здесь)](https://drive.google.com/drive/folders/1aeCi27q8hp8lrdXChdIQsuafGv3-21iO?usp=sharing), не удалось запустить утилиту lcov для генерации html-отчета о покрытии кода

**Comment by leshastern** [comment]
Удалось построить отчет
[клик](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/files/4531532/report.zip)
