### ISSUE TITLE
Исследовать возможности раздела Wiki Github.

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#242]
# Срок сдачи: 28.04.20
###Epic: #211 
_Пояснения_: Нужно найти информацию по этому разделу (https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/wiki), как с ним работать, приложить ссылки на эту информацию. Перенести все документы, созданные по задачам #226  #227  #228  #229. 
 Туда, красиво и понятно все оформить.
Возможности раздела [Wiki](https://github.com/docops-hq/learnapidoc-ru/blob/master/Publishing-doc/Manage-wiki-content.md) Github.
[Документация](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/wiki) по задачам #226 #227 #228 #229.

**Comment by Sergey-student** [comment]
[https://github.com/docops-hq/learnapidoc-ru/blob/master/Publishing-doc/Manage-wiki-content.md](url)

**Comment by Sergey-student** [comment]
https://github.com/docops-hq/learnapidoc-ru/blob/master/Publishing-doc/Manage-wiki-content.md

**Comment by None-stopCoding** [comment]
по задаче нужно перенести все доки отсюда (#226 #227 #228 #229) в wiki.

**Comment by None-stopCoding** [comment]
продляем срок по задаче, она зависит от выполнения других задач

**Comment by Sergey-student** [comment]
[Документация по задачам](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/wiki)

**Comment by Sergey-student** [comment]
Возможности раздела [Wiki](https://github.com/docops-hq/learnapidoc-ru/blob/master/Publishing-doc/Manage-wiki-content.md)
