### ISSUE TITLE
Выпустить новый пре-релиз продукта

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#248]
### Epic: #34 
_Пояснения_:
Наш проект существует вот уже долгие полгода и всё это время мы уверенными шагами шли к его завершению. Месяцы работы, бесчисленные часы труда, ссоры и расставания — всё это легло костьми во благо завершения нашего труда. И вот теперь, наконец, мы подобрались к финишной черте, долгожданному пре-релизу. Одно движения для и огромный шаг для всей команды. В такие моменты чувствуешь себя Нилом Армстронгом от мира IT. Воистину непередаваемые ощущения, компенсирующие все невзгоды, что выпали на мою голову за время работы. Непередаваемое ощущение, которое должен ощутить каждый хотя бы раз в жизни.

Теперь, когда пре-релиз лежит уже у наших ног, я бы хотел сказать спасибо. Спасибо всей нашей команде: Анастасии Вохмяниной — за мудрое и долгое руководство, Алексею Жукову — за то, что удержал на себе наш проект и не позволил команде поредеть, Альберту Шаброву и Максиму Буханову — за неоспоримый вклад в области разработки, Сергею Коломейчуку — за написание полезной документации и Алексею Смирнову — за непревзойдённость в сфере написанию юнит-тестов. Ребята, без вас этого бы не случилось! Ну и, конечно, главная наша благодарность, несравнимая с чьей-либо ещё, оттдаётся Юрию Викторовичу, нашему вспыльчивому, но мудрому и терпеливому руководителю, направлявшего всё это время наши усилия в благое русло. Спасибо! Всем спасибо!

Пре-релиз уже ждёт своего шанса увидеть свет, и совсем скоро это, наконец свершится! Нам остаётся лишь терпеливо работать, чтобы он в вышел в мир прекрасным лебедем, а не гадким больным утёнком, вызывающим лишь чувство отторжения. Пожелаю же себе и другим удачи в этом нелёгком деле. Спасибо  за внимание.

**Comment by Someone-dono** [comment]
По общему согласованию было решено перенести задачу на следующий спринт.

**Comment by YuriSilenok** [comment]
> По общему согласованию было решено перенести задачу на следующий спринт.

я не вижу в истории изменений атрибутов этой задачи того, что она была в предыдущем спринте

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.
