### ISSUE TITLE
Рефакторинг функций парсинга принятых сообщений

### ISSUE THREAD

**Issue by SkinnerX7** [Students-of-the-city-of-Kostroma/trpo_automation#25]
### Пересмотреть подход к обработке сырых сообщений. 
Рефакторинг алгоритмов извлечение поля "Body" из сообщения. 
Интегрировать изменения в функцию: 
- work_EmailLibrary.py

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by VladmirV** [comment]
Приступаю к выполнению

**Comment by VladmirV** [comment]
Создана ветка issue-25

**Comment by VladmirV** [comment]
Завершаю выполнение

**Comment by YuriSilenok** [comment]
Если вы что-то оптимизируете, значит должны быть количественные замеры работы чего-то до оптимизации и после оптимизации.
