### ISSUE TITLE
Обработка ошибки в ходе работы программы

### ISSUE THREAD

**Issue by cyberAndrey** [Students-of-the-city-of-Kostroma/trpo_automation#252]
В случае сбоя в работе системы студенты, чьи письма проверялись, должны получить уведомление о сбое и просьбу прислать работу повторно.
Также техподдержка должна получить сведения об ошибке, чтобы знать что исправлять

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by cyberAndrey** [comment]
> Пожалуйста, добавьте веху к этой задаче

Сделал, но тут только прошлый спринт

**Comment by YuriSilenok** [comment]
Если веха существует для старого спринта, то следует создать новую, а все не заверенные задачи старого спринта, нужно перенести в бэклог. А так же проставить метки спринта в которых по этой задаче была активность.

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой не указан дедлайн

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.
