### ISSUE TITLE
Написать сценарии для тестов класса Functional

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#253]
### Epic: #36 
_Пояснения_: Сценарии тестирования разработаны, результаты можно посмотреть [здесь](https://docs.google.com/spreadsheets/d/1d4DwpPxyc5DkmKFavszVM5prBqGhY7CCWIz_CnZOHEs/edit?usp=sharing)

**Comment by leshastern** [comment]
Сценарии тестирования разработаны, результаты можно посмотреть [здесь](https://docs.google.com/spreadsheets/d/1d4DwpPxyc5DkmKFavszVM5prBqGhY7CCWIz_CnZOHEs/edit?usp=sharing)
 @None-stopCoding проверь

**Comment by None-stopCoding** [comment]
нужно по каждому методу, их 5

**Comment by YuriSilenok** [comment]
кажется эта задача является источник для задачи по автоматизации этих тестов, но на эту задачу ссылка на ведет. пожалуйста, найдите ее и свяжите их.

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.
