### ISSUE TITLE
Заполнение функционала. Base. Формирование JSON. Этап 2

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#255]
Заменить существующие на настоящие момент заглушки в функциях первого релиза на реально требующийся функционал, описанный в комментариях к функциям

Файл:
- trpo_automation/email/18-ISbo-2b/base_WorkWithLetters.py

Текущая функция:
- FormJSONDates(letters)

Связанные задачи:
- #111 

Что предусмотреть:
- Релиз находится на вкладке "Releases" либо в ветке 18-ISbo-2b
- Спецификация по методу находится в его описании
- Тестирование работы своей функциональности проводить самостоятельно, запуская релиз в работу
- Изменить иерархию папок в ветке Base (перенести структуру из ветки 18-ISbo-2b и добавить в конечной папке папку tmp, в которую переместить все существующие наработки) 
- Настройка структуры проводится один раз на модуль
  
Результаты будут ожидаться в виде pull request ов в ветку Base

**Comment by Tim-Shelll** [comment]
Изменил иерархию папок
Перенес все наработки на ветку Base

**Comment by urec-programmec** [comment]
Задача закрывается, т.к. был замёрджен pr
