### ISSUE TITLE
Найти аналоги системы

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#255]
# Срок сдачи: 11.06.20
### Epic: #34 
_Пояснения_:

**Comment by YuriSilenok** [comment]
как мне больно смотреть на эти задачи

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by Someone-dono** [comment]
Аналоги были найдены, о них было рассказано на презентации.

С материалом можно ознакомиться по ссылке:  https://docs.google.com/document/d/1G8WyW3PiEELcpuslyulEVladHjf2QBmP5X4apfHKqfM/edit?usp=sharing

**Comment by YuriSilenok** [comment]
> Аналоги были найдены, о них было рассказано на презентации.
> 
> С материалом можно ознакомиться по ссылке: https://docs.google.com/document/d/1G8WyW3PiEELcpuslyulEVladHjf2QBmP5X4apfHKqfM/edit?usp=sharing

Пожалуйста, используйте гиперссылки для предоставления url на источник.
![image](https://user-images.githubusercontent.com/14871471/85198718-9c760a00-b2f3-11ea-857b-e102350083c9.png)

**Comment by Someone-dono** [comment]
[Аналоги](https://docs.google.com/document/d/1G8WyW3PiEELcpuslyulEVladHjf2QBmP5X4apfHKqfM/edit?usp=sharing) были найдены, о них было рассказано на презентации.
