### ISSUE TITLE
Попарное тестирование. Автотесты протокола общения

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#257]
### Epic: #36 
_Пояснения_: Необходимо уменьшить количество кейсов путем создание определенных условий с помощью утилиты pict

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.
