### ISSUE TITLE
Заполнение функционала. Google. Формирование списка писем. Этап 2

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#258]
Заменить существующие на настоящие момент заглушки в функциях первого релиза на реально требующийся функционал, описанный в комментариях к функциям

Файл:
- trpo_automation/email/18-ISbo-2b/google_CheckEmail.py

Текущая функция:
- FormListWithLetters(letters)

Связанные задачи:
- #116

Что предусмотреть:
- Релиз находится на вкладке "Releases" либо в ветке 18-ISbo-2b
- Спецификация по методу находится в его описании
- Тестирование работы своей функциональности проводить самостоятельно, запуская релиз в работу
- Изменить иерархию папок в ветке 18-ISbo-2b_google (перенести структуру из ветки 18-ISbo-2b и добавить в конечной папке папку tmp, в которую переместить все существующие наработки).
- Настройка структуры проводится один раз на общую ветку 18-ISbo-2b_google
  
Результаты будут ожидаться в виде pull request ов в ветку Base

**Comment by VladmirV** [comment]
Задача была начата. Наличие функции комментирования благополучно забыто.

**Comment by VladmirV** [comment]
Первый этап завершен. Формирования экземпляров без учета кодов ошибок.

**Comment by VladmirV** [comment]
Тестирование первого этапа.
![image](https://user-images.githubusercontent.com/55273743/80392289-9ea18680-88b7-11ea-8edb-452eac142c84.png)

**Comment by VladmirV** [comment]
@urec-programmec 
Завершаю выполнение.
