### ISSUE TITLE
Заполнение функционала. Google. Проверка пользователей. Этап 3

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#259]
Заменить существующие на настоящие момент заглушки в функциях первого релиза на реально требующийся функционал, описанный в комментариях к функциям

Файл:
- trpo_automation/email/18-ISbo-2b/google_CheckEmail.py

Текущая функция:
- CheckUsers(letters)

Связанные задачи:
- #24 #147 #190

Что предусмотреть:
- Релиз находится на вкладке "Releases" либо в ветке 18-ISbo-2b
- Спецификация по методу находится в его описании
- Тестирование работы своей функциональности проводить самостоятельно, запуская релиз в работу
- Изменить иерархию папок в ветке 18-ISbo-2b_google (перенести структуру из ветки 18-ISbo-2b и добавить в конечной папке папку tmp, в которую переместить все существующие наработки).
- Настройка структуры проводится один раз на общую ветку 18-ISbo-2b_google
  
Результаты будут ожидаться в виде pull request ов в ветку Base

**Comment by CatherinePRO** [comment]
Мужчина, какие вообще письма... Вы о чем?

**Comment by CatherinePRO** [comment]
"""
    Функционал:
    - Проверить зарегистрированность каждого пользователя в системе по email - реализовано
    На входе:
    - Список писем??? нет у меня его, есть email
    На выходе:
    - Расставленное поле 'isRegistered' в каждом письме в поле 'User'
   !!!! Нет у меня писем!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by CatherinePRO** [comment]
Есть Функция на входе EMAIL, на выходе ФИО или FALSE

**Comment by CatherinePRO** [comment]
со списком писем не ко мне!

**Comment by urec-programmec** [comment]
Задача принимается
