### ISSUE TITLE
Компоновка приватных функций Email функционала

### ISSUE THREAD

**Issue by SkinnerX7** [Students-of-the-city-of-Kostroma/trpo_automation#26]
Вынести приватные функции E-mail функционала в отдельный пакет. Адаптировать следующие функции под внесенные изменения:
- main_1_google_CheckEmail.py
- main_5_send_InformUsers.py

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by VladmirV** [comment]
Приступаю к выполнению

**Comment by VladmirV** [comment]
Создана ветка issue-26

**Comment by VladmirV** [comment]
Завершаю выполнение задачи

**Comment by YuriSilenok** [comment]
Во втором коммит вы писали что исправили баг, что это за баг?

**Comment by VladmirV** [comment]
Скорее всего не так выразился. В первом коммите упустил одну строчку импорта. Во втором добавил ее.

**Comment by YuriSilenok** [comment]
Избегайте слово баг, оно должно присутствовать в метках. В вашем случае вы исправили синтаксические ошибки или добавили импорт пакета
