### ISSUE TITLE
Заполнение функционала. Google. Валидация писем. Этап 4

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#260]
Заменить существующие на настоящие момент заглушки в функциях первого релиза на реально требующийся функционал, описанный в комментариях к функциям

Файл:
- trpo_automation/email/18-ISbo-2b/google_CheckEmail.py

Текущая функция:
- ValidateLetters(letters)

Связанные задачи:
- #22 #188 

Что предусмотреть:
- Релиз находится на вкладке "Releases" либо в ветке 18-ISbo-2b
- Спецификация по методу находится в его описании
- Тестирование работы своей функциональности проводить самостоятельно, запуская релиз в работу
- Изменить иерархию папок в ветке 18-ISbo-2b_google (перенести структуру из ветки 18-ISbo-2b и добавить в конечной папке папку tmp, в которую переместить все существующие наработки).
- Настройка структуры проводится один раз на общую ветку 18-ISbo-2b_google
  
Результаты будут ожидаться в виде pull request ов в ветку Base

**Comment by cyberAndrey** [comment]
Изменил правила написания [писем](https://docs.google.com/document/d/1YMtlwsImBzR1ONhY6hH0VZnonpRmHM9UZ0glsG8sMLA/edit#)
Но тема остается открытой

**Comment by cyberAndrey** [comment]
Сделал пул реквест с гтовой работой в ветку base

**Comment by urec-programmec** [comment]
Задача закрывается, т.к. была реализована (в ветке 18-ISbo-2b_google)
