### ISSUE TITLE
Написать сценарии и автотесты по ним StrategyLab (context)

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#260]
### Epic: #36 
_Пояснения_: Разработать сценарии тестирования и автотесты для метода StrategyLab::checkContext();

**Comment by MaksimBukhanov** [comment]
Сценарии тестирования разработаны.
С результатом работы можно ознакомиться [здесь](https://docs.google.com/spreadsheets/d/1d4DwpPxyc5DkmKFavszVM5prBqGhY7CCWIz_CnZOHEs/edit#gid=146939622).

**Comment by YuriSilenok** [comment]
Максим, Вы написали что выполнили задачу, но не перевести на проверяющего, почему?

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.
