### ISSUE TITLE
Заполнение функционала. Google. Выставление оценок. Этап 5

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#261]
Заменить существующие на настоящие момент заглушки в функциях первого релиза на реально требующийся функционал, описанный в комментариях к функциям

Файл:
- trpo_automation/email/18-ISbo-2b/send_SetResults.py

Текущая функция:
- SetMarks(letterResults)

Связанные задачи:
- #106 #190

Что предусмотреть:
- Релиз находится на вкладке "Releases" либо в ветке 18-ISbo-2b
- Спецификация по методу находится в его описании
- Тестирование работы своей функциональности проводить самостоятельно, запуская релиз в работу
- Изменить иерархию папок в ветке 18-ISbo-2b_google (перенести структуру из ветки 18-ISbo-2b и добавить в конечной папке папку tmp, в которую переместить все существующие наработки).
- Настройка структуры проводится один раз на общую ветку 18-ISbo-2b_google
  
Результаты будут ожидаться в виде pull request ов в ветку Base

**Comment by CatherinePRO** [comment]
def SetMarks(letterResults):
    """
     Функционал:
    - Выставить необходимые оценки в журнал - ФУНКЦИЯ РЕАЛИЗОВАНА
    На входе: !!!НЕТ У МЕНЯ ПИСЕМ
    - letterResults - заполненный и проверенный список писем - экземпляров класса LetterResults

**Comment by urec-programmec** [comment]
Задача принята
