### ISSUE TITLE
Автоматизировать генерацию отчетов о тестировании по выпуску пре-релиза

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#262]
### Epic: #36
_Пояснения_: Речь о создании нового листа с таблицей пройденных тестов в гугл таблице Сценарии тестирования

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.
