### ISSUE TITLE
Заполнение функционала. Google. Отправка ответов. Этап 6

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#262]
Заменить существующие на настоящие момент заглушки в функциях первого релиза на реально требующийся функционал, описанный в комментариях к функциям

Файл:
- trpo_automation/email/18-ISbo-2b/send_InformUsers.py

Текущая функция:
- SendLetters(answersForUsers)

Связанные задачи:
- #24

Что предусмотреть:
- Релиз находится на вкладке "Releases" либо в ветке 18-ISbo-2b
- Спецификация по методу находится в его описании
- Тестирование работы своей функциональности проводить самостоятельно, запуская релиз в работу
- Изменить иерархию папок в ветке 18-ISbo-2b_google (перенести структуру из ветки 18-ISbo-2b и добавить в конечной папке папку tmp, в которую переместить все существующие наработки).
- Настройка структуры проводится один раз на общую ветку 18-ISbo-2b_google
  
Результаты будут ожидаться в виде pull request ов в ветку Base

**Comment by VladmirV** [comment]
Начало выполнения.

**Comment by VladmirV** [comment]
Добавлен функционал авторизации.

**Comment by VladmirV** [comment]
Добавлена отправка сообщений.

**Comment by VladmirV** [comment]
@urec-programmec 
Завершаю выполнение.

**Comment by VladmirV** [comment]
Тесты не выявили ошибок. @urec-programmec, проверьте корректность заполнения экземпляров AnswersForUsers.
![image](https://user-images.githubusercontent.com/55273743/81073400-3fafc300-8ef0-11ea-9ae6-9d1d00817d2c.png)
![image](https://user-images.githubusercontent.com/55273743/81073438-50f8cf80-8ef0-11ea-8873-724b5eaa4857.png)
![image](https://user-images.githubusercontent.com/55273743/81073477-5d7d2800-8ef0-11ea-87bc-f50c2b501439.png)
