### ISSUE TITLE
Автоматизировать выгрузку результатов авто тестирования в таблицу Сценариев

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#263]
### Epic: #36 
_Пояснения_: по выпуску пре-релиза внутри CI выполнить скрипт для выставления Passed/Failed напротив автотестовс тегом пре-релиза в таблице Сценарии тестирования

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-263 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-263 давно не было активности

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-263 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-263 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-263 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-263 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-263 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-263 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-263 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-263 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-263 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-263 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-263 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-263 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-263 давно не было активности

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.
