### ISSUE TITLE
выпуск пре-релиза по реквесту в dev

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#264]
### Epic: #35 
_Пояснения_: Настроить секцию CI в dev.xml, чтобы при реквесте ветки в dev, выпускался пре-релиз (зашифровать ключ Github token)

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.
