### ISSUE TITLE
построить use case диаграмму

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#267]
### Epic:  #37 
_Пояснения_: Разработать Use Case диаграмму

**Comment by MaksimBukhanov** [comment]
Разработана диаграмма Use Case
С результатом работы можно ознакомиться [здесь](https://app.diagrams.net/#G1gDol1Spa7gEK73nPAbKtCV84Am55W2Ex)

**Comment by YuriSilenok** [comment]
Проектная документация после реализации проекта, миленько. Зачем её делать сейчас, если она вам не понадобилась?

**Comment by None-stopCoding** [comment]
Пусть будет, лишним не станет)) Тем более, она у нас была, все это время, в голове)

**Comment by YuriSilenok** [comment]
> Пусть будет, лишним не станет)) Тем более, она у нас была, все это время, в голове)

Так какого она там была, сидим у нас были люди которым нечем было загяться?
