### ISSUE TITLE
Разработать структуру модуля

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#27]
Архитектура, взаимосвязь, иерархия классов модуля.

Задача назначена на один спринт. Больше времени этому уделяться не будет

**Comment by Progoger** [comment]
Задание выполнил Гусев Артём, прикрепляю ссылку для проверки выполнения:https://drive.google.com/drive/u/0/folders/1If6XZeMkUzFZq8CMNrp8k6XDYhe1g3t-

**Comment by urec-programmec** [comment]
Комментирую
Структура модуля включает в себя весь заявленный в [диаграмме](https://www.draw.io/#G1uBk9EZCwKGp3pa4MURUgB9tz5a2x9DN_) функционал
Что такое модуль — ссылка [тут](https://docs.google.com/document/d/1VnIuTmjycBvwvyfVx-RJl1hDfTVA0YoDg1v0tsyrhQA/edit)

Что имеется сейчас — 4 класса, которые не способны выполнять свою функциональную нагрузку

Что ожидается — более подробное изучение идеи модульной разработки и разаботка UML диаграммы, исходя уже из чёткого понимания задачи. Помимо этого в пояснительной записке должен быть чётко описан цикл вызовов методов

**Comment by urec-programmec** [comment]
Закрыто за потерей актуальности
