### ISSUE TITLE
 покрыть сценариями getRequest

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#270]
### Epic: #36 
_Пояснения_: прикрепить ссылку на документ, в котором будут находиться сценарии тестирования метода getRequest

**Comment by YuriSilenok** [comment]
Нет описания к ссылке.

**Comment by AnastasiVokhmyanina28** [comment]
[ссылка](https://docs.google.com/spreadsheets/d/1d4DwpPxyc5DkmKFavszVM5prBqGhY7CCWIz_CnZOHEs/edit?usp=sharing)

**Comment by YuriSilenok** [comment]
> [ссылка](https://docs.google.com/spreadsheets/d/1d4DwpPxyc5DkmKFavszVM5prBqGhY7CCWIz_CnZOHEs/edit?usp=sharing)

этого недостаточно для описания ссылки.

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.
