### ISSUE TITLE
 покрыть сценариями  getCode

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#274]
### Epic: #36 
_Пояснения_: [ссылка](https://docs.google.com/spreadsheets/d/1d4DwpPxyc5DkmKFavszVM5prBqGhY7CCWIz_CnZOHEs/edit?usp=sharing)  на документ в Google Drive, где будут расположены сценарии тестирования метода getCode

**Comment by YuriSilenok** [comment]
Дайте описание содержимому ссылки в описании этой задачи.

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.
