### ISSUE TITLE
Cпецификация JSON

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#28]
Закончить документацию по JSON
Написать единый документ формата

Лабораторная работа № N
Порт № Z
Формат JSON:
{
...
}

**Comment by urec-programmec** [comment]
Принял результаты через Вконтакте
Презентация [здесь](https://docs.google.com/presentation/d/1dQ9rwSkHJOVe4mQOJdMzmxA_TbwCOrXUCuktlhyW3eg/edit#slide=id.g7ed27e09f8_0_60)
Задача ожидает корректировки со стороны ВТ

**Comment by urec-programmec** [comment]
Информация по поводу портов

Порты
18-ВТбо-1а - [10000-10999]
18-ВТбо-1б - [11000-11999]
18-ИСбо-2а - [12000-12999]
18-ИСбо-2б - [13000-13999]

**Comment by SkinnerX7** [comment]
Выполнил стандарт JSON 
Ссылка на документ: https://docs.google.com/document/d/18wjwqCfr148crAN2Glso_a0bkwB36QitpP-h4bHFz7Q/edit

**Comment by urec-programmec** [comment]
После обсуждения на предыдущей паре данного вопроса изменяю задачу и назначаю исполнителем себя

**Comment by urec-programmec** [comment]
Закончил общую структуру

**Comment by urec-programmec** [comment]
Закончил с расстановкой форматов JSON
Документ [здесь](https://docs.google.com/document/d/1UWPYAc9Qqtg3XbEyg5CfDk6F5vaSsirt08Jx3DZSYD4/edit)

**Comment by urec-programmec** [comment]
Исправил замечания, обсудил результаты проверки.
