### ISSUE TITLE
Разработать часть диаграммы классов.

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#280]
### Epic:  #37 
_Пояснения_: Добавить класс Functional на диаграмму классов

**Comment by MaksimBukhanov** [comment]
Класс Functional добавлен на диаграмму классов.
С результатом можно ознакомиться [здесь.](https://app.diagrams.net/#G1tQpqPwSX5Lu-Ad_0zKHSn5MYBLQ-SEWj)

**Comment by MaksimBukhanov** [comment]
Задача выполнена.
С результатом работы можно ознакомиться [здесь.](https://drive.google.com/file/d/1kazl61uOHD_cMOpki6B0OZzPeQaQeJZq/view?usp=sharing)

**Comment by YuriSilenok** [comment]
> Задача выполнена.
> С результатом работы можно ознакомиться [здесь.](https://app.diagrams.net/#G1kazl61uOHD_cMOpki6B0OZzPeQaQeJZq)

ссылка не работает.
вам нужно получать ее с гугл диска, а не с адресной строки браузера

**Comment by MaksimBukhanov** [comment]
> > Задача выполнена.
> > С результатом работы можно ознакомиться [здесь.](https://app.diagrams.net/#G1kazl61uOHD_cMOpki6B0OZzPeQaQeJZq)
> 
> ссылка не работает.
> вам нужно получать ее с гугл диска, а не с адресной строки браузера

Ссылка исправлена
