### ISSUE TITLE
Написать диаграмму классов для TcpServer

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#282]
### Epic:  #37 
_Пояснения_:  для защиты проекта необходимо написать диаграммы классов для класса TcpServer

**Comment by AlbertShabrov** [comment]
Диаграмма классов для TcpServer можно посмотреть [здесь](https://drive.google.com/file/d/1kazl61uOHD_cMOpki6B0OZzPeQaQeJZq/view?usp=sharing)

**Comment by AlbertShabrov** [comment]
Задача решена, комментарий с ссылкой на диаграмму классов сверху
