### ISSUE TITLE
Не парсит labNumber

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#282]
# Срок сдачи:  15.04.20
### Epic: #210 
_Пояснения_:ожидаемый результат (ОР): число парсится и записывается в переменную labNumber
фактический результат (ФР): число не парсится, хотя в приходящем json поле соответствующее есть, а labNumber остается с инициализированным ранее значением

**Comment by AlbertShabrov** [comment]
Проверили на правильность парсинга json строки и пришли к выводу, что проблема была ни в неправильном парсинге а в неправильной передаче данных. Отправляли следующие данные {"data": "content", "labNumber": "7"}, при парсинге labNumber считал "7" как строку, поэтому и выводил заранее инициализированный 0 после того, как отрабатывал метод. Необходимо было отправлять данные следующим образом send {"data": "content", "labNumber": 7}, тогда все работает правильно.
