### ISSUE TITLE
Обеспечить Unit-тестирование метода поиска группы и ФИО по email

### ISSUE THREAD

**Issue by MoL4okkk** [Students-of-the-city-of-Kostroma/trpo_automation#284]
Написать автотесты для метода search_group (файл APIgoogle).

**Comment by 0Meridian0** [comment]
метод сделан проверить можно [здесь](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/blob/issue-234/email/18-ISbo-2a/Test_google.py)
название: test_search_group

**Comment by Svyat935** [comment]
Задача выполнена.
