### ISSUE TITLE
Развернуть локальный веб-сервер

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#29]
Локальный веб-сервер для изучения взаимодействия с ним

Результаты представить в виде настроенной веб страницы локального хоста (к примеру 127.0.0.1 или 192.168.0.1)

**Comment by urec-programmec** [comment]
Не наблюдаю комментария о проделанной работе
Задача отсылается в To do

**Comment by Progoger** [comment]
Написал простой сервер на питоне, взял данные этого сервера и передал их на веб-страницу.
Закидываю в preview done

**Comment by urec-programmec** [comment]
Принято. До встречи на демке
