### ISSUE TITLE
 Инициализировать проект

### ISSUE THREAD

**Issue by None-stopCoding** [Students-of-the-city-of-Kostroma/trpo_automation#3]
Срок завершения работ по задаче: 20.03.20

**Comment by YuriSilenok** [comment]
Непонятна чуть задачи, что залить и почему на это нужна задача, все должно попадать на гит, кто отвественный

**Comment by TsaplinK** [comment]
Этапы
1: Разработать систему веток, создать базу в git
2: Всем разработчикам установить Qt Creator и познакомиться с фреймворком Qt 5
3: Создать тестовую базу

**Comment by None-stopCoding** [comment]
[Git Flow 18-vt-a](https://codesandbox.io/s/git-flow-18-vt-a-dnjwg)

**Comment by YuriSilenok** [comment]
> [Git Flow 18-vt-a](https://codesandbox.io/s/git-flow-18-vt-a-dnjwg)

зачем это?

**Comment by None-stopCoding** [comment]
Это первый пункт по задаче - разработана системам веток.

**Comment by None-stopCoding** [comment]
Разрабы опрошены - пункт 2 выполнен. Пункт 3 - не имеет смысла (при создании не обговорили необходимость)
