### ISSUE TITLE
Изучить работу с http запросами

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#30]
Имитация работы с веб-сервером
Стадии работы:

- изучить работу с отправкой http запросов в python.

Результаты работы представить в виде листа документации или рабочего метода

- послать http запрос, получить ответ на запрос от веб-сервера

Результаты представить в виде работающего метода

- послать JSON, получить ответ на запрос от веб-сервера

Результаты представить в виде работающего метода

**Comment by urec-programmec** [comment]
Ожидаю комментариев о проделанной работе

**Comment by Progoger** [comment]
Добавлен Сервер-"Server.py"
Добавлены отправка http-запроса и отправка json-"HTTPReq.py"
Общие классы перенесены в папку "CommonClasses"

**Comment by Progoger** [comment]
Разделил один файл HTTPReq на два HTTPReq(http-запрос), JSONSend(отправка JSON)

**Comment by urec-programmec** [comment]
Принял pull request
