### ISSUE TITLE
Заполнение функционала. Global. Таймер

### ISSUE THREAD

**Issue by cyberAndrey** [Students-of-the-city-of-Kostroma/trpo_automation#309]
Заменить существующие на настоящие момент заглушки в функциях первого релиза на реально требующийся функционал, описанный в комментариях к функциям

Файл:

    trpo_automation/email/18-ISbo-2b/global_Timer.py

Текущие функции:

    SetTimer()
    WaitForTimer()

Тестирование работы своей функциональности проводить самостоятельно, запуская релиз в работу

**Comment by cyberAndrey** [comment]
Написал два варианта действия таймера
Ветка issue-309

**Comment by urec-programmec** [comment]
Задача закрывается, т.к. была реализована
