### ISSUE TITLE
Настроить сервер на получение данных согласно протоколу и их обратную отправку

### ISSUE THREAD

**Issue by avilova** [Students-of-the-city-of-Kostroma/trpo_automation#314]
[Протокол](https://docs.google.com/document/d/1ZmBVhi1C9-qt0iu5U3TLLPWadmDhe414nYaskIKHmPE/edit#heading=h.gzrywaomqvkt)

**Comment by Dudka567** [comment]
Сервер настроен на  получение данных согласно протоколу и обратно.
