### ISSUE TITLE
Разработать сценарии тестирования протокола передачи данных в виде гугл таблицы

### ISSUE THREAD

**Issue by avilova** [Students-of-the-city-of-Kostroma/trpo_automation#315]
[Протокол](https://docs.google.com/document/d/1ZmBVhi1C9-qt0iu5U3TLLPWadmDhe414nYaskIKHmPE/edit#heading=h.gzrywaomqvkt). В дальнейшем предоставить готовую таблицу тестировщику.
[Сценарий тестирования протокола передачи данных](https://docs.google.com/spreadsheets/d/173fcVRsMoGgEgocefV-_fLICh7-Jk9ukjcRUyW3-4ec/edit#gid=0)

**Comment by vvtatyana** [comment]
[Сценарий тестирования протокола передачи данных](https://docs.google.com/spreadsheets/d/173fcVRsMoGgEgocefV-_fLICh7-Jk9ukjcRUyW3-4ec/edit#gid=0)

**Comment by avilova** [comment]
Проверила, принято
