### ISSUE TITLE
 Разработать сценарии тестирования лабораторной работы в виде гугл таблицы.

### ISSUE THREAD

**Issue by avilova** [Students-of-the-city-of-Kostroma/trpo_automation#316]
По итогу предоставить отчет о выполнении тестов, готовые сценарии,

**Comment by Llouqs** [comment]
[Сценарии тестирования лабораторной работы №3](https://docs.google.com/spreadsheets/d/1BehPksH9vwqt16_Lcn1_w6ch0CbvUhUXSw0Ao9yzVDQ/edit#gid=0)

**Comment by avilova** [comment]
Проверила, принято

**Comment by avilova** [comment]
Проверила, принято

**Comment by avilova** [comment]
Задача сделана не до конца, остается за @Llouqs.
