### ISSUE TITLE
Написать тестовые письма

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#32]
Написать различные тестовые письма

- не меньше десяти
- письма должны быть сформированы по разным шаблонам, с разными ошибками для тестирования системы валидации

Результаты представить в виде файла на Google Disk

**Comment by cyberAndrey** [comment]
[Документ](https://docs.google.com/document/d/1knlDwZ4lGp7NlXlYRQp_11sQAKZlG4qBdP2qyhC0TQY/edit#heading=h.xzwb24pmw5e7)

**Comment by urec-programmec** [comment]
Задание проверил
На текущий спринт задание закрыто
Задание остаётся в разработку на последующие спринты

**Comment by urec-programmec** [comment]
Закрыто из за потери приоритетности
