### ISSUE TITLE
Протестировать пре-релиз v.0.0.0.4

### ISSUE THREAD

**Issue by Svyat935** [Students-of-the-city-of-Kostroma/trpo_automation#325]
Протестировать пре-релиз v.0.0.0.4 на все возможные пользовательские сценарии.
При возникновение отклонения от сценария постараться исправить

**Comment by Sirokko77** [comment]
Тестирование закончено.
Результаты тестирования:
- Туева хуча ошибок по мелочи
- Неправильное возвращение названия таблицы
- Не выставляется 0 при ошибках в работе
- Программа не может отправить работу на проверку, если ошибки в валидации
- В письме имя указывается в ковычках
- Несогласованности в сценариях
- Шифровка
- Не работает валидация ссылки

**Comment by ShapovalovQ** [comment]
Провёл тестирование [данного сценария](https://docs.google.com/document/d/1nUm8dr_woo-hrjc2FEDLUImEEAfbVzkqWTOVG_kDj8E/edit?usp=sharing) и ,помимо выше перечисленных, нашёл следующие ошибки:
- "Здравствуйте" и "Доброе утро" не считаются приветствиями, хотя 2-ое, возможно, и не особо уместно, но, всё же, имеет право на жизнь
- Не проверяется номер лабораторной работы, то есть если в теме будет "ТРПО ЛР№124124" письмо будет обрабатываться
- Проверяется лишь наличие подписи, а не её суть

**Comment by Svyat935** [comment]
Задача выполнена.
