### ISSUE TITLE
Unit-тесты для метода SendJSONForCheck

### ISSUE THREAD

**Issue by Progoger** [Students-of-the-city-of-Kostroma/trpo_automation#328]
Написать unit-тесты для метода SendJSONForCheck, тем самым проверив его работоспособность и правильность.

**Comment by Progoger** [comment]
Написал один пробный unit-тесты, он лежит в ветке issue-328

**Comment by urec-programmec** [comment]
Задача закрывается, т.к. был замёрджен pr
