### ISSUE TITLE
Сформировать общедоступный модуль глобальных классов

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#33]
Написать один модуль в понятии python (отдельный файл), содержащий описание общедоступных методов

Методы связи: 

- Letter
- LetterResult
- AnswersForUsers

Глобальный класс

- User

Результаты представить в виде отдельного пакета питона, способного к подключению в другие модули с описанием представленных классов внутри

**Comment by Progoger** [comment]
Выполнил, пока без описания имеющихся классов, если всё нормально, дорабатываю описание

**Comment by Progoger** [comment]
Ветка: issue-33

**Comment by Progoger** [comment]
Добавил описание классов

**Comment by Progoger** [comment]
Исправлено описание так, как сказал Юрий Викторович

**Comment by urec-programmec** [comment]
Добавить pull request

**Comment by Progoger** [comment]
Добавил pull request
