### ISSUE TITLE
Доработка продукта и выкат релизной версии

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#35]
Написание службы
Развернуть службу на удаленном сервере

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Какие есть обновления по этой задаче?

**Comment by YuriSilenok** [comment]
@None-stopCoding Это не является эпиком

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.
