### ISSUE TITLE
Описать категории писем

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#36]
Описать различные категории писем
Сопоставить код и реальное состояние.
Получить информацию у команды Google либо решить задачу совместно

К примеру, письмо не зачтено по причине того, что пользователь не зарегистрирован в системе

Результаты представить в виде документа на Google Disk

**Comment by BlackReper086** [comment]
Шаблоны сохранены на [Google Drive](https://drive.google.com/open?id=1I20MJTDv4RmFZNJQEfeGhtcd4N9tj4xC). Требуется проверка.

**Comment by urec-programmec** [comment]
Проверил, отправлено на доработку

**Comment by BlackReper086** [comment]
Уменьшил длину кода до 2 символов. Разделил на категории: ошибки (00-09), нейтральные результаты (10-19), успех(20-29), резерв (30-99). Требуется проверка

**Comment by urec-programmec** [comment]
Ссылка на нужный документ
[Коды](https://drive.google.com/file/d/1teHvhrZZOLNP5cWcR7rntGVakC1fje1Q/view)

**Comment by urec-programmec** [comment]
Задача принята

**Comment by urec-programmec** [comment]
Перезалито на GD в формате Google Таблицы
[Ссылка](https://docs.google.com/spreadsheets/d/1o6pLF4PXGc6h6X7q4epYjuzTCzZmDobuR0on4av4wO4/edit#gid=1847888026)

**Comment by urec-programmec** [comment]
Перезалито на GD в формате Google Документы
[Ссылка](https://docs.google.com/document/d/11wergOjZTa9mxJ_jn8ZqnYSBYRqcSNhE/edit#heading=h.gjdgxs)
