### ISSUE TITLE
Реализовать различные шаблоны писем разных категорий

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#37]
Написать шаблоны писем, отсылаемых пользователям с результатами проверки в соответствии с заданной категорией
Не забыть про уведомление преподавателей как отдельную единицу

Результаты представить в виде документа на Google Disk

**Comment by BlackReper086** [comment]
Написать шаблон писем для разработчиков

**Comment by BlackReper086** [comment]
Шаблоны сохранены на [Google Drive](https://drive.google.com/open?id=11wergOjZTa9mxJ_jn8ZqnYSBYRqcSNhE). Требуется проверка. Требуется уточнить структуру письма разработчикам.

**Comment by urec-programmec** [comment]
Проверил
Обсудил с исполнителем места на доработку
Отправил на доработку

**Comment by BlackReper086** [comment]
Убраны письма о отправке работы и в процессе проверки. Более формальные темы писем. Присвоен код к каждому письму(кроме писем разработкам). Требуется проверка.

**Comment by urec-programmec** [comment]
Задание выполнено верно. 
Теперь ожидаю документ, перезалитый на Google Drive в ту же папку, но в формате Google документа а не документа .docx

**Comment by urec-programmec** [comment]
Кроме этого когда задание выполнено и требует проверки, оно должно находиться в колонке Preview done. 
Перетаскивать задачи можно самому.

**Comment by urec-programmec** [comment]
Перезалито на GD в формате Google Документы
[Ссылка](https://docs.google.com/document/d/11wergOjZTa9mxJ_jn8ZqnYSBYRqcSNhE/edit#heading=h.gjdgxs)
