### ISSUE TITLE
Реализовать класс тестов для проверки класса Selenium 

### ISSUE THREAD

**Issue by DanilKozlov00** [Students-of-the-city-of-Kostroma/trpo_automation#376]
Написать тесты с покрытием не менее 50%, результаты тестирования использовать в таблице #316

**Comment by DanilKozlov00** [comment]
[Результаты](https://codecov.io/gh/DanilKozlov00/SeleniumIntegrationTest/src/master/src/main/java/Selenium.java) покрытия кода тестами

**Comment by avilova** [comment]
Проверила, принято
