### ISSUE TITLE
Разработка проверок лабораторных работ по паттерну "Стратегия"

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#38]
Описание: задача не актуальна, сдача проекта успешно состоялось

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by AnastasiVokhmyanina28** [comment]
Задача не актуальна. создана одна общая (https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/issues/35)

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте описание к этой задаче

**Comment by AnastasiVokhmyanina28** [comment]
Задача не актуальна.
объединена  с задачей (https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/issues/35)
