### ISSUE TITLE
Переписать план разработки и тестирования

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#39]
# Срок сдачи: 09.06.20
### Epic: #37 
_Прогресс по задаче_:  https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/issues/39#issuecomment-641727974

**Comment by AlbertShabrov** [comment]
Ссылка на [План разработки и тестирования функционала](https://docs.google.com/spreadsheets/d/1a_--ME6oOIIhx96Qhk0eT2gAFmpyy0wmOE6e3usJ8Dk)

**Comment by leshastern** [comment]
На Review назначен @YuriSilenok

**Comment by YuriSilenok** [comment]
> На Review назначен @YuriSilenok

Эта фраза должна была быть в виде просьбы. 
Это не связано с требованиями лично ко мне.
Это часть любой корпоративной этики.
То есть, Ваша фраза должна выглядеть приблизительно следующим образом.
> Могли бы проверить [План разработки и тестирования функционала](https://docs.google.com/spreadsheets/d/1a_--ME6oOIIhx96Qhk0eT2gAFmpyy0wmOE6e3usJ8Dk) ?

В идеальном случае, нужно поздороваться и сказать спасибо, как в письме.

**Comment by YuriSilenok** [comment]
> Ссылка на [План разработки и тестирования функционала](https://docs.google.com/spreadsheets/d/1a_--ME6oOIIhx96Qhk0eT2gAFmpyy0wmOE6e3usJ8Dk)

если вы публикуете важные материалы в комментариях, они должны дублироваться в описание задачи

**Comment by YuriSilenok** [comment]
> На Review назначен @YuriSilenok

В целом мне непонятно какие мне (как пользователю) функции разрабатывались и протестировались. по сути вы создали документ в котором расписали цели и задачи каждого спринта. Это не совсем то, так как у нас много всего косвенного в них и формулировки относятся не к функциям пользователя, а к методам ваших классов, вообщем к архитектуре.

**Comment by None-stopCoding** [comment]
На 10 спринт [план разработки и тестирования](https://docs.google.com/spreadsheets/d/1a_--ME6oOIIhx96Qhk0eT2gAFmpyy0wmOE6e3usJ8Dk/edit?usp=sharing) был дополнен.
@YuriSilenok Прошу посмотреть, документ открыт для комментирования. Спасибо!

**Comment by None-stopCoding** [comment]
@YuriSilenok Посмотрите пожалуйста

**Comment by YuriSilenok** [comment]
Почему используются различные по размеру шрифты для однотипных ячеек?
Для чего объединялись ячейки?
Нужно заполнить недостающие спринты

**Comment by None-stopCoding** [comment]
Недостающие спринты - для какой цели заполняем?
Шрифты поправил

**Comment by YuriSilenok** [comment]
> Недостающие спринты - для какой цели заполняем?
> Шрифты поправил

Я предполагаю что Вы могли бы показать эти планы на презентации на генеральной демке

**Comment by None-stopCoding** [comment]
@YuriSilenok Поправил пункты [плана](https://docs.google.com/spreadsheets/d/1a_--ME6oOIIhx96Qhk0eT2gAFmpyy0wmOE6e3usJ8Dk/edit?usp=sharing), добавил информацию по недостающим спринтам, привел пункты плана к одному виду, посмотрите пожалуйста.

**Comment by YuriSilenok** [comment]
Пусть будет так
