### ISSUE TITLE
Создать клиент, отправляющий работу на проверку

### ISSUE THREAD

**Issue by Sirokko77** [Students-of-the-city-of-Kostroma/trpo_automation#4]
Необходимо создать компонент, позволяющий отправить запрос на проверку работ по TCP в компонент проверяющий лабораторную работу.

На вход принимается либо ссылка на лабораторную работу, либо на файл. В любом случае необходимо составить json файл для последующей отправки на проверку.

Также на вход принимается номер лабораторной работы для определения порта сервера.

Основной метод должен возвращать значения 0 и 1, где 0 - работа не выполнена, либо возникла ошибка, а 1 - работа выполнена и засчитана.

**Comment by YuriSilenok** [comment]
Задача поставлена 6 дней назад, к какой команде она относится?

**Comment by YuriSilenok** [comment]
@Sirokko77  Зачем на меня назначена эта задача?
что с задачей?

**Comment by Sirokko77** [comment]
Задача выполнена
