### ISSUE TITLE
Дописать сценарии тестирования gateway

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#40]
# Срок сдачи: 23.05.20
### Epic: #37 
_Пояснения_: [ссылка на документ](https://docs.google.com/spreadsheets/d/160h_F-RDIiDb4j5kd-Rqa0mxjpDZ15lUMpbGdVuPLhg/edit?usp=sharing)

**Comment by leshastern** [comment]
[ссылка на документ](https://docs.google.com/spreadsheets/d/160h_F-RDIiDb4j5kd-Rqa0mxjpDZ15lUMpbGdVuPLhg/edit?usp=sharing)

**Comment by YuriSilenok** [comment]
Некорректно перевешивает на человека задачу, не указав что он должен с ней сделать.

**Comment by YuriSilenok** [comment]
> [ссылка на документ](https://docs.google.com/spreadsheets/d/160h_F-RDIiDb4j5kd-Rqa0mxjpDZ15lUMpbGdVuPLhg/edit?usp=sharing)

Выглядит хорошо.
Подумайте над тем, как представить информацию о том, что покрывают эти тесты.

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте метки в вашу задачу

**Comment by AnastasiVokhmyanina28** [comment]
метка добавлена
