### ISSUE TITLE
Разработка сценариев тестирования.

### ISSUE THREAD

**Issue by Svyat935** [Students-of-the-city-of-Kostroma/trpo_automation#408]
Задача:
Разработать сценарии тестирование [по примеру](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit)

**Comment by Sirokko77** [comment]
Сценарии были написаны. Посмотреть можно [тут](https://drive.google.com/open?id=1z9PipsTgDDl6ThdCMPsLjjg5Ial9JdCBzd0NXQ1jHrI)

**Comment by Svyat935** [comment]
Задача выполнена.
