### ISSUE TITLE
Написать службу

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#41]
# Срок сдачи: 25.05.20
### Epic: #35 
_Пояснения_: :)

**Comment by MaksimBukhanov** [comment]
Приняли решение использовать утилиту start-stop-daemon в Ubuntu.
[Пользовательская документация start-stop-daemon](https://help.ubuntu.ru/wiki/start-stop-daemon)
