### ISSUE TITLE
Разработать сценарий для лабораторной работы №3

### ISSUE THREAD

**Issue by DanilKozlov00** [Students-of-the-city-of-Kostroma/trpo_automation#41]

**Comment by YuriSilenok** [comment]
где описание задачи, ссылка документ со сценариями, ссылку на описание лабораторной работы?

**Comment by vvtatyana** [comment]
[Сценарий лабораторной работы](https://docs.google.com/document/d/1HwiwtyuUKBC38tDCYTeOGleCW8atKlELT9Ipd4pJCBo/edit)
