### ISSUE TITLE
Улучшить методы работы с Gmail API.

### ISSUE THREAD

**Issue by Svyat935** [Students-of-the-city-of-Kostroma/trpo_automation#411]
Задача:
- Попытаться реализовать отправку письма связанной с пришедшим письмом(цепочка писем)
- Поставить метку ТРПО на письме.
- Сделать пример письма, которая отправляет список лабораторных. (?)
- Отключить цепочки писем на мыле.
- Архивация письма сразу после ответа.(?)
- Отметить письмо, что производиться его чтение.
- Настроить метки на мыле

? - задача может быть нереализована по причине другого подхода.

**Comment by 0Meridian0** [comment]
- Цепочка писем не реализована (API не позволяет)
- Метка "ТРПО" теперь есть в темах писем
- 
- Цепочки писем отключены
- Архивация отправленного сообщения не реализована(API не позволяет)
- Теперь метка UNREAD снимается при получении информации из письма
- Настроен триггер на метку "ТРПО"

**Comment by Svyat935** [comment]
Задача закрыта
