### ISSUE TITLE
Устранить ошибку

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#420]
# Срок сдачи: 26.04.20
### Epic: #209 
_Пояснения_: ФР: не компилируется проект

![HV-iT9ve3KI](https://user-images.githubusercontent.com/55682455/80309383-04691200-87d5-11ea-9f1f-45a1957c3562.jpg)

ОР: ошибка не вылетает

**Comment by AlbertShabrov** [comment]
Ошибка в компиляции объекта класса GateWay, ответственный за него Алексей Жуков, ему и передаю эту задачу
