### ISSUE TITLE
Написать документацию по модульным тестам, как их запускать локально

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#440]
# Срок сдачи: 03.05.20
### Epic: #211 
_Пояснения_:
[Документация](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/wiki/Локальный-запуск-модульных-тестов)

**Comment by Sergey-student** [comment]
[Локальный запуск модульных тестов](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/wiki/Локальный-запуск-модульных-тестов)
