### ISSUE TITLE
Отчет по полному тестированию

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#45]
### Epic: #37 
_Пояснения_: прикрепить ссылку на документ
[Документация](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/wiki/Сервер)

**Comment by ghost** [comment]
[Документация](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/wiki/Сервер)

**Comment by YuriSilenok** [comment]
Против какой версии выполнялись тесты для которых был составлен отчет?
Каким образом в википедии вы будете учитывать версии?
Разве я не давал табличный шаблон отчета в котором была указана версия?

**Comment by AnastasiVokhmyanina28** [comment]
Задача перенесена (https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/issues/191)
