### ISSUE TITLE
Разработать сценарий для лабораторной работы №5

### ISSUE THREAD

**Issue by vvtatyana** [Students-of-the-city-of-Kostroma/trpo_automation#498]
Написать сценарии для 15 вариантов лабораторной работы №5 в гугл документе.
[Сценарий лабораторной работы №5](https://docs.google.com/document/d/16mrQO3Pw7Gpfej-ETHbZbrOQ2vOeJlMRjL0jliKbqPY/edit)

**Comment by avilova** [comment]
принято
