### ISSUE TITLE
Валидация письма

### ISSUE THREAD

**Issue by MaXL2000** [Students-of-the-city-of-Kostroma/trpo_automation#5]
Создать класс, принимающий тело письма и его тема. Проверить правильно ли указана тема письма к конкретной лабораторной работе. Проверить поздоровался ли пользователь. Проверить подпись.

**Comment by YuriSilenok** [comment]
К какой команде относится эта задача?

**Comment by MaXL2000** [comment]
К команде Смирнова Александра и Обидина Никиты

**Comment by YuriSilenok** [comment]
Проверяю на соответствие [шаблону](https://docs.google.com/document/d/1DRhgepxVwoscylIS2LCW-po5SFBdqOr-oo92bP_XfHE/edit?usp=sharing)

**Comment by YuriSilenok** [comment]
какие изменения по этой задаче?

**Comment by Svyat935** [comment]
Задача продлена на третий спринт.

**Comment by Svyat935** [comment]
@MaXL2000 Состояние задачи ?

**Comment by MaXL2000** [comment]
Выполняется

**Comment by YuriSilenok** [comment]
Судя по истории этой задаче, я закрыл эту задачи.
Это было обоснованно?

**Comment by Svyat935** [comment]
Да, валидация была выполнена. 
Почему закрыли именно вы - так как просто навсего её забыли закрыть.
