### ISSUE TITLE
Сценарии тестирования функции SetMarks

### ISSUE THREAD

**Issue by SkinnerX7** [Students-of-the-city-of-Kostroma/trpo_automation#5]
Написать сценарии тестирования функции SendLetters по аналогии с уже существующими в [документе](https://docs.google.com/spreadsheets/d/1IHaHZS0_vT2SRZCWRdLPDvhNNvPcKf5QjA6GztFQgF4/edit?usp=sharing)
- Входные данные должны быть разного типа (как принимаемые для обработки этой функцией, так и непринимаемые)
- Входные данные должны быть корректными (ожидаемыми после отработки предыущей функции)
- В Input и в Output данные должны быть расписаны с нужной детализацией (важные в этой функции поля)

**Comment by CatherinePRO** [comment]
[в документе](https://docs.google.com/spreadsheets/d/1IHaHZS0_vT2SRZCWRdLPDvhNNvPcKf5QjA6GztFQgF4/edit#gid=208599158)
test_S_8_t1
test_S_8_t2
test_S_8_t3
test_S_8_t4

**Comment by urec-programmec** [comment]
Задача принята
