### ISSUE TITLE
Валидация писем

### ISSUE THREAD

**Issue by CatherinePRO** [Students-of-the-city-of-Kostroma/trpo_automation#504]
Не соответствие функционала ТЗ. Реализовать проверку соответствия имени и фамилии пользователя прикрепленному к email (информацию брать из аккаунта гугл) с данными, содержащимися в таблице ответов!

**Comment by cyberAndrey** [comment]
Баг пофикшен. Файл с измененным кодом в ветке issue-504

**Comment by CatherinePRO** [comment]
задача принята, выполнено слияние
