### ISSUE TITLE
Некорректное выполнение функции SendJSONForCheck()

### ISSUE THREAD

**Issue by SkinnerX7** [Students-of-the-city-of-Kostroma/trpo_automation#522]
Не происходит заполнение экземпляров классов LetterResult при обработке писем с кодом, отличным от "20"

**Comment by CatherinePRO** [comment]
не работает, требуются правки. на выходе для всех должен быть заполнен экземпляр класса letterResult

**Comment by SkinnerX7** [comment]
Приступил к работе
