### ISSUE TITLE
Написать план тестирования

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#532]
# Срок сдачи: 10.05.20
### Epic: #209 
_Пояснения_:  [ссылка на документ](https://docs.google.com/spreadsheets/d/1mCuW4ViaK2I_ciNBP2jhDR92hQnQjKu6tw2zr4KPVEo/edit?usp=sharing)

**Comment by leshastern** [comment]
План тестирования доступен  [здесь](https://docs.google.com/spreadsheets/d/1mCuW4ViaK2I_ciNBP2jhDR92hQnQjKu6tw2zr4KPVEo/edit?usp=sharing) (первый лист)

**Comment by YuriSilenok** [comment]
Все важные ссылки должны содержаться в описании задачи

**Comment by leshastern** [comment]
> Все важные ссылки должны содержаться в описании задачи

@YuriSilenok, теперь можно закрыть?

**Comment by AnastasiVokhmyanina28** [comment]
Задача не актуальна. создана общая задача (https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/issues/579)
