### ISSUE TITLE
Написать план разработки функциональности

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#533]
# Срок сдачи:  13.05.20
### Epic: #2 
_Пояснения_: прикрепить ссылку на документ

**Comment by AlbertShabrov** [comment]
[План разработки функциональности](https://docs.google.com/document/d/1OOlzcv1Jj-6p1_JeBHUrjeIP1nj-dNQYUZNLA_Y4CRU)

**Comment by AnastasiVokhmyanina28** [comment]
Задача не актуальна. создана  общая задача (https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/issues/579)
