### ISSUE TITLE
Описать структуру конфига проекта

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/trpo_automation#54]
Необходимо учесть в конфиге:
- сопоставление лабораторной работы и порта
- токен для гугл
- ид журнала
- ид таблицы регистрации

**Comment by ComButterbrot** [comment]
Ссылка на [информацию](https://drive.google.com/drive/folders/1AySUzSenJhsfD-t1xxChlgt8LWQ0y8oL).

**Comment by Svyat935** [comment]
Задача выполнена.
