### ISSUE TITLE
Написать методичку описывающую использование  сервиса Travis 

### ISSUE THREAD

**Issue by DanilKozlov00** [Students-of-the-city-of-Kostroma/trpo_automation#540]
[Методичка](https://drive.google.com/open?id=1sbdCrJDpQBc5VvlEM2NKhPecw8oto-12dmeiFVEd6X8)

**Comment by DanilKozlov00** [comment]
[Методичка](https://drive.google.com/open?id=1sbdCrJDpQBc5VvlEM2NKhPecw8oto-12dmeiFVEd6X8)

**Comment by YuriSilenok** [comment]
не нужно делать метки спринтов непосредственно для группы ВТ.
проект позволит понять что эта задача относится к группе вт

**Comment by YuriSilenok** [comment]
> [Методичка](https://drive.google.com/open?id=1sbdCrJDpQBc5VvlEM2NKhPecw8oto-12dmeiFVEd6X8)

результаты перенести в описание задачи

**Comment by DanilKozlov00** [comment]
Исправил

**Comment by avilova** [comment]
принято
