### ISSUE TITLE
Исправить заполнение ответов для отправки

### ISSUE THREAD

**Issue by CatherinePRO** [Students-of-the-city-of-Kostroma/trpo_automation#543]
MakeAnswersForUsers работает не правильно. Не верный перебор и заполнение ответов для отправки
#97 #270

**Comment by BlackReper086** [comment]
Ошибки исправил. Жду проверки.

**Comment by BlackReper086** [comment]
Исправлено. Изменения сохранены

**Comment by CatherinePRO** [comment]
коммит замерджен, ветка удалена, считаем задачу закрытой
