### ISSUE TITLE
Исправление валидации писем (код статус)

### ISSUE THREAD

**Issue by CatherinePRO** [Students-of-the-city-of-Kostroma/trpo_automation#544]
При проверке письма в гугл документе, помеченного проходящим валидацию - возвращает код статус 02. Смотри письмо по форме в почте бота

**Comment by cyberAndrey** [comment]
Те письма были неактуальными. Изменил на [актуальные](https://docs.google.com/document/d/1knlDwZ4lGp7NlXlYRQp_11sQAKZlG4qBdP2qyhC0TQY/edit#heading=h.ifmxd5kje4q0)
