### ISSUE TITLE
Некорректное значение поля Body при получении писем

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#547]
После  функции GetLetters в поле Body письма есть лишняя информация, не относящаяся к телу входного письма
![image](https://user-images.githubusercontent.com/54985070/81492571-90813c00-92a1-11ea-851f-9a16dfe3fc45.png)

Кроме этого, обрати внимание на мини-баг.
Здесь не должно быть заполнения этого поля
![image](https://user-images.githubusercontent.com/54985070/81492598-c2929e00-92a1-11ea-9080-038a9509ecc7.png)

**Comment by VladmirV** [comment]
Закрыто по причине потери актуальности.
