### ISSUE TITLE
Баг в методе Validate_Letters()

### ISSUE THREAD

**Issue by SkinnerX7** [Students-of-the-city-of-Kostroma/trpo_automation#55]
Исправить баг:
- Заполнение CommentCodeStatus в случаях неправильного указания номера лабораторной и варианта
Не соответствие сценария и поведения самой функции 
Связанные тесты: test_S_3_t7  test_S_3_t8

**Comment by SkinnerX7** [comment]
Открываю снова задачу, баг не исправлен
![image](https://user-images.githubusercontent.com/55276061/83155960-7b623500-a10a-11ea-8fa6-8d4e48d80208.png)

**Comment by YuriSilenok** [comment]
А на основании какого теста или сценария был открыт, закрыт и переоткрыть этот баг?

**Comment by YuriSilenok** [comment]
Баги должен закрывать тот, кто его открыл, именно он решает, исправлен баг или нет

**Comment by YuriSilenok** [comment]
Добрый день. Вы не удалили ветку issue-55 и закрыли задачу

**Comment by YuriSilenok** [comment]
Хотелось бы увидеть комментарий закрывавшего этот баг, о том, в какой версии был исправлен баг?

**Comment by YuriSilenok** [comment]
Какие есть обновления по этой задаче?

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by SkinnerX7** [comment]
Баг был исправлен в версии v0.0.0.6
