### ISSUE TITLE
Добавить логи в код email read, send client, send mark in sheet

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/trpo_automation#55]
Добавить логи в прикрепленных линках запросов на слияние

**Comment by YuriSilenok** [comment]
ваша задача будент может быть зхакрыта только после мержа запросов и закрытия запросов и задач связанных с этой задачей. В вашем случае все три мержа все еще открыты

**Comment by YuriSilenok** [comment]
вы видели что запросы на слияния завершены?

**Comment by magnitola** [comment]
da

**Comment by YuriSilenok** [comment]
> da

Тогда почему задача открыта?
