### ISSUE TITLE
Добавление студента в журнал

### ISSUE THREAD

**Issue by CatherinePRO** [Students-of-the-city-of-Kostroma/trpo_automation#57]
Автоматизировать добавление студента в журнал (в случае, если он там отсутствует) на этапе выставления оценок

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by urec-programmec** [comment]
Задача принята. 
Отдано на тестирование

**Comment by YuriSilenok** [comment]
Добрый день. Вы не удалили ветку issue-57 и закрыли задачу

**Comment by urec-programmec** [comment]
Задача выполнена - принята
