### ISSUE TITLE
Разработать структуру логов

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#58]
- выделить необходимые уровни логирования

- выделить для каждого уровня необходимые метрики, по которым будет производиться сбор данных (т.е. что в конечном итоге будет собираться)

- выделить структуру хранения логов

Результаты представить в виде листа документации, которая будет стандартом для описания логов

**Comment by BlackReper086** [comment]
Документ сохранил на [Google Drive](https://drive.google.com/open?id=1_0wGJbMO4SctmNRMTFkDYaOhgvOVKfpT8hklMQCNxEg). Требуется проверка.

**Comment by urec-programmec** [comment]
Задача решена верно.
Разработанная структура является стандартом логов в нашей части проекта

**Comment by BlackReper086** [comment]
Добавить данные в Info.
