### ISSUE TITLE
Написать шаблон письма на новый код

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#596]
Появилось новое состояние письма:
- Ссылки, представленные в письме некорректны 

Требуется написать шаблон ответного письма пользователю по аналогии с уже [созданными](https://docs.google.com/document/d/12mSzNBvU_WRPhW6snqCZLgmx2ziJRMnahdztMTvb8wk/edit)
 
Новый код - '08'

**Comment by BlackReper086** [comment]
[Документ](https://drive.google.com/file/d/11wergOjZTa9mxJ_jn8ZqnYSBYRqcSNhE/view) изменён. Ожидаю проверки.

**Comment by urec-programmec** [comment]
Подкорректировал.
Задача принимается
