### ISSUE TITLE
Получение email из полученного письма

### ISSUE THREAD

**Issue by 0Meridian0** [Students-of-the-city-of-Kostroma/trpo_automation#6]
Разработать метод обработки письма:
На вход дается письмо на gmail, на выходе получаем email отправителя этого письма

**Comment by YuriSilenok** [comment]
К какой команде относится эта задача?

**Comment by YuriSilenok** [comment]
Причина закрытия задачи?

**Comment by 0Meridian0** [comment]
задача закрыта, так как была реализована сразу с другой

**Comment by YuriSilenok** [comment]
В таком случае необходимо указывать номер задачи. Что бы можно было найди   эти изменения

**Comment by 0Meridian0** [comment]
Задача реализована в issue-17
