### ISSUE TITLE
Закончить написание unit тестов 

### ISSUE THREAD

**Issue by SkinnerX7** [Students-of-the-city-of-Kostroma/trpo_automation#6]
Дополнительно проверить соответствие тестов сценариям

(1) CheckUsers
(2) ValidateLetters
(3) LettersConvertToString
(4) FormJSONDates
(5) SendJSONForCheck
(6) SetMarks
(7) MakeAnswersForUsers
(8) SendLetters

**Comment by SkinnerX7** [comment]
(1) CheckUsers
(2) ValidateLetters
Забрал эти функции на тестирование

**Comment by SkinnerX7** [comment]
На функции 
- CheckUsers()
- ValidateLetters()
Были написаны unittest'ы

**Comment by VladmirV** [comment]
Написаны тесты на функции:
- SendLetters #83 
- FormListWithLetters #84

**Comment by YuriSilenok** [comment]
Пожалуйста, приведите статистику покрытия тестами проекта и в часности покрытых методов

**Comment by SkinnerX7** [comment]
Статистика по unittest'ам находится [здесь](https://docs.google.com/spreadsheets/d/1IHaHZS0_vT2SRZCWRdLPDvhNNvPcKf5QjA6GztFQgF4/edit#gid=208599158)

**Comment by YuriSilenok** [comment]
Это статистика по автоматизации, на неё так же нужно было оствать ссылку. Я спрашивал статистику по покрытия код. Она будет говорить о полноте ваших тестов.

**Comment by SkinnerX7** [comment]
Отчёт по покрытию проекта:
[01.06.2020_Покрытие](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/files/4711843/01.06.2020_.zip)
![image](https://user-images.githubusercontent.com/55276061/83419982-998fa400-a42e-11ea-91e7-7838ea39303e.png)
