### ISSUE TITLE
Указывается неверный текст сообщения в ответе на письмо отправителя в цепочке писем

### ISSUE THREAD

**Issue by Svyat935** [Students-of-the-city-of-Kostroma/trpo_automation#60]
Реализация бага:

1. Отправить письмо на почту.
2. Ответить на письмо с почты.

Ожидаемый результат:
Цитата должна быть на письмо пользователя.
Результат:
Цитата произошла на письмо бота, а не на письмо пользователя.

**Comment by 0Meridian0** [comment]
в ходе работы с задачей #59  баг не был выявлен

**Comment by YuriSilenok** [comment]
Заголовок бага не должен содержать предписания о том, что нужно сделать.

**Comment by 0Meridian0** [comment]
@YuriSilenok, заголовок исправлен

**Comment by YuriSilenok** [comment]
Заголовок бага должен отвечать на три вопроса. Что? Где? Когда?
Ознакомьтесь с [этим](https://m.habr.com/ru/company/docsvision/blog/264163/) документом

**Comment by 0Meridian0** [comment]
@YuriSilenok, исправлено
