### ISSUE TITLE
Сценарии тестирования функции LettersConvertToString

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#607]
Написать сценарии тестирования в [документе](https://vk.com/away.php?utf=1&to=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1IHaHZS0_vT2SRZCWRdLPDvhNNvPcKf5QjA6GztFQgF4%2Fedit%3Fusp%3Dsharing) (лист 2)

Рассмотреть несколько (по возможности не меньше пяти-семи различных) ситуаций входных данных
Данные должны быть как корректными, так и некорректными, но допустимыми (чтобы все входные данные были ожидаемыми после отработки предыдущих функций)

Этому документу впоследствии сопоставить unit тесты с соответствующим названием

**Comment by Progoger** [comment]
Сценарии готовы, https://docs.google.com/spreadsheets/d/1IHaHZS0_vT2SRZCWRdLPDvhNNvPcKf5QjA6GztFQgF4/edit#gid=208599158
Строки 36-40

**Comment by urec-programmec** [comment]
Задача принята
Проверить соответствие существующих unit тестов документу или создать их при необходимости
Поднять задачу, указать в ней ссылку на эту задачу
