### ISSUE TITLE
Сценарии тестирования к модулям.

### ISSUE THREAD

**Issue by Svyat935** [Students-of-the-city-of-Kostroma/trpo_automation#61]
Написать сценарии тестирования к модулям. 
[Пример реализации](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=1813879881)

Документ положить в информацию на google drive.

**Comment by ComButterbrot** [comment]
Таблица со сценариями доступна по [ссылке](https://docs.google.com/spreadsheets/d/1mUQV1-A-Ot8gCa-DOvklq-Umv5BCR8wd51V6PTGUI48/edit?usp=sharing).

**Comment by YuriSilenok** [comment]
Правильно разместить сценарии

**Comment by YuriSilenok** [comment]
Какие есть обновления по этой задаче?

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта
