### ISSUE TITLE
Реализовать репозитории на GitHub согласно сценариям

### ISSUE THREAD

**Issue by DanilKozlov00** [Students-of-the-city-of-Kostroma/trpo_automation#61]

**Comment by HozookiSan** [comment]
[Вариант_1](https://github.com/HozookiSan/Losyash.git)

**Comment by HozookiSan** [comment]
[Вариант_2](https://github.com/HozookiSan/Krosh.git)

**Comment by HozookiSan** [comment]
[Вариант_3](https://github.com/HozookiSan/Yozhik.git)

**Comment by HozookiSan** [comment]
[Вариант_4](https://github.com/HozookiSan/Barash.git)

**Comment by HozookiSan** [comment]
[Вариант_5](https://github.com/HozookiSan/Nusha.git)

**Comment by HozookiSan** [comment]
[Вариант_6](https://github.com/HozookiSan/Pin.git)

**Comment by HozookiSan** [comment]
[Вариант_7](https://github.com/HozookiSan/Sovunya.git)

**Comment by HozookiSan** [comment]
[Вариант_8](https://github.com/HozookiSan/Pandi.git)

**Comment by HozookiSan** [comment]
[Вариант_9](https://github.com/HozookiSan/Kar-Karych.git)

**Comment by DanilKozlov00** [comment]
[Тесты](https://docs.google.com/document/d/1MdNoKPLF1NMY_PTO67v4EvTaC3JS6Zzc/edit)
