### ISSUE TITLE
Непрервная интеграция Azura или Travis

### ISSUE THREAD

**Issue by Svyat935** [Students-of-the-city-of-Kostroma/trpo_automation#62]
Непрерывная интеграция(автоматические пре-релизы и автотесты) должны быть исправлены на Azure, или перейти на Travis. 

- [x] Настроить автотесты.

- [x] Настроить авто-выкат пре-релиза

- [x] Настроить идентификаторы в автотестах

- [x] Продемонстрировать работу тимлиду

**Comment by Svyat935** [comment]
Возникла проблема относительный и абсолютным импортов.

**Comment by YuriSilenok** [comment]
Какие есть обновления по этой задаче?

**Comment by Svyat935** [comment]
Забыли закрыть задачу.

Выполнено.
