### ISSUE TITLE
Отчет по тестированию.

### ISSUE THREAD

**Issue by Svyat935** [Students-of-the-city-of-Kostroma/trpo_automation#63]
Выполнить отчет по тестированию пре-релиза v.0.0.0.10.

Полезные ссылки:
[Презентация](https://docs.google.com/presentation/d/1JMExLGZyFPtQcOfz5fJFjTx-9jVvsIii6Lavm7TBQcA/edit#slide=id.p1)
[Пример в excel](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=1813879881)

**Comment by Sirokko77** [comment]
Тестирование закончено. Результаты представлены в [данной таблице](https://docs.google.com/spreadsheets/d/1z9PipsTgDDl6ThdCMPsLjjg5Ial9JdCBzd0NXQ1jHrI/edit#gid=0)

**Comment by YuriSilenok** [comment]
> Тестирование закончено. Результаты представлены в [данной таблице](https://docs.google.com/spreadsheets/d/1z9PipsTgDDl6ThdCMPsLjjg5Ial9JdCBzd0NXQ1jHrI/edit#gid=0)

Я не увидел здесь никакого отчёта о тестировании, кто у вас это проверял?

**Comment by LegendaRepa** [comment]
Был написан отчет о тестировании, доступен по [этой ссылке](https://docs.google.com/spreadsheets/d/1eIdSnxK18t0z_uImSGkyt4bOVZ5Ft3EX_A-tTElHM90/edit#gid=0)
Для тестов использовались [данные сценарии](https://docs.google.com/spreadsheets/d/1z9PipsTgDDl6ThdCMPsLjjg5Ial9JdCBzd0NXQ1jHrI/edit#gid=0)

P.S. По глупости спросонья удалил ваш комментарий, хотел найти кнопку ответа на него, но не получилось не фартануло

**Comment by YuriSilenok** [comment]
В сценариях так же нужно указывать для какого релиза вы указываете статус выполнения теста

**Comment by Svyat935** [comment]
Ожидание модульных сценариев и добавление отчета по ним.

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by YuriSilenok** [comment]
Пожалуйста, добавьте веху к этой задаче

**Comment by LegendaRepa** [comment]
Было проведено тестирование новейшей версии. Отчет о тестировании можно посмотреть [тут](https://docs.google.com/spreadsheets/d/1eIdSnxK18t0z_uImSGkyt4bOVZ5Ft3EX_A-tTElHM90/edit?usp=sharing)
