### ISSUE TITLE
Улучшить валидацию.

### ISSUE THREAD

**Issue by Svyat935** [Students-of-the-city-of-Kostroma/trpo_automation#64]
Улучшить всю валидацию:

- [x] Увеличить выборку валидных примеров.

- [x] Прикрутить регулярные выражения

**Comment by MaXL2000** [comment]
Попытался добавить регулярки в метод валидации. Не смог подобрать оптимальные регулярные выражения для корректной валидации приветствия, подписи и номера лабораторной.

**Comment by YuriSilenok** [comment]
Покажите варианты для которых вы составляет регулярку и те регулярки, которые у вас получились

**Comment by Svyat935** [comment]
В помощь добавляется Никита Обидин.

**Comment by MaJishpro** [comment]
Переписал метод валидации с применением регулярных выражений [в](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/blob/issue-64/email/18-ISbo-2a/Validation.pyl)

**Comment by YuriSilenok** [comment]
> Переписал метод валидации с применением регулярных выражений [Посмотреть здесь](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/blob/issue-64/email/18-ISbo-2a/Validation.pyl)

ссылка не работает и нет связанного запроса на слияние

**Comment by MaJishpro** [comment]
Переписал метод валидации с применением регулярных выражений [Посмотреть здесь](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/blob/issue-64/email/18-ISbo-2a/Validation.py)

**Comment by YuriSilenok** [comment]
> Переписал метод валидации с применением регулярных выражений [Посмотреть здесь](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/blob/issue-64/email/18-ISbo-2a/Validation.py)

Нехорошо удалять комментарии, его нужно было отредактировать, а на мой комментарий ответить, что исправлено

А почему ссылка ведет на ветку группы, разве вы не вносили какие-то изменения в отдельную ветку которая должна проверятся запросом на слияние?

**Comment by MaJishpro** [comment]
> > Переписал метод валидации с применением регулярных выражений [Посмотреть здесь](https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/blob/issue-64/email/18-ISbo-2a/Validation.py)
> 
> Нехорошо удалять комментарии, его нужно было отредактировать, а на мой комментарий ответить, что исправлено
> 
> А почему ссылка ведет на ветку группы, разве вы не вносили какие-то изменения в отдельную ветку которая должна проверятся запросом на слияние?

Я залил изменения на ветку issue-64 . А запрос на слияние мне сказали пока не делать.

**Comment by YuriSilenok** [comment]
Какие есть обновления по этой задаче?

**Comment by Svyat935** [comment]
Забыли закрыть задачу.

Выполнено.
