### ISSUE TITLE
Написать инструкцию по пользованию системы.

### ISSUE THREAD

**Issue by Svyat935** [Students-of-the-city-of-Kostroma/trpo_automation#65]
Требуется написать инструкцию по пользованию системы, которая будет описывать варианты пользования для пользователя.
Документ положить на google drive

**Comment by magnitola** [comment]
Задача выполнена. Найти написанный документ можно [*здесь*](https://docs.google.com/document/d/1hBDNeyM34TOxDyIQziurNWDs2Et8xog09v4E2tLGs9Y/edit)

**Comment by YuriSilenok** [comment]
Данный документ разместить в вашей рабочей папке под именем READMY.md
