### ISSUE TITLE
Поправить модули в APIgoogle.

### ISSUE THREAD

**Issue by Svyat935** [Students-of-the-city-of-Kostroma/trpo_automation#67]
Нужно поправить модули: 

- [x] add_table

- [x] search_dolgi

Поправить обращение к Excel, чтобы не было лишних временных затрат.

**Comment by YuriSilenok** [comment]
В ветке issue-67 давно не было активности

**Comment by Svyat935** [comment]
Не было активности по причине её выполнения.

**Comment by Svyat935** [comment]
Задача выполнена.
