### ISSUE TITLE
Поправить методы на основе новой таблицы.

### ISSUE THREAD

**Issue by Svyat935** [Students-of-the-city-of-Kostroma/trpo_automation#68]
Подправить методы связанные с поиском, добавлением, просчетом долгов на основе нового вида таблицы.

**Comment by YuriSilenok** [comment]
В ветке issue-68 давно не было активности

**Comment by Svyat935** [comment]
Не было - по причине выполнения.

**Comment by Svyat935** [comment]
Задача выполнена.
