### ISSUE TITLE
Разработка заглушки для сервера

### ISSUE THREAD

**Issue by ShapovalovQ** [Students-of-the-city-of-Kostroma/trpo_automation#7]
Разработать сервер, который получает некоторые входные данные от клиента, а затем рандомно отправляет ему 0 или 1 в виде JSON.

**Comment by YuriSilenok** [comment]
К какой команде относится эта задача и кто ответственный за нее?

**Comment by ShapovalovQ** [comment]
18-ИСбо-2а Шаповалов В.

**Comment by YuriSilenok** [comment]
> 18-ИСбо-2а Шаповалов В.

1. Вы не указали Ваше имя и фамилию в гихаб
