### ISSUE TITLE
Разработать шаблон писем

### ISSUE THREAD

**Issue by 0Meridian0** [Students-of-the-city-of-Kostroma/trpo_automation#78]
Написать шаблон для писем:
1. Письмо не прошло авторизацию
2. Письмо не прошло валидацию
3. В лабораторной работе имеются ошибки
4. Работа принята

**Comment by YuriSilenok** [comment]
нет ссылки на результаты

**Comment by 0Meridian0** [comment]
Ссылка на шаблоны писем в GD
https://docs.google.com/document/d/12a3RU3ZGSdKiSx-n4b8T2KO-b40wL6MpF5t_uh2tD7o/edit?usp=sharing
