### ISSUE TITLE
Unit-тесты на функцию SetMarks

### ISSUE THREAD

**Issue by cyberAndrey** [Students-of-the-city-of-Kostroma/trpo_automation#79]
Написать тесты по [сценариям тестирования](https://docs.google.com/spreadsheets/d/1IHaHZS0_vT2SRZCWRdLPDvhNNvPcKf5QjA6GztFQgF4/edit#gid=208599158) строка 64

**Comment by SkinnerX7** [comment]
Связанная задача #6

**Comment by YuriSilenok** [comment]
Добрый день. Вы не удалили ветку issue-79 и закрыли задачу

**Comment by cyberAndrey** [comment]
> Добрый день. Вы не удалили ветку issue-79 и закрыли задачу

Увидел, исправил
