### ISSUE TITLE
Реализовать unit-тесты на функцию FormListWithLetters

### ISSUE THREAD

**Issue by VladmirV** [Students-of-the-city-of-Kostroma/trpo_automation#84]
Реализовать unit-тесты на функцию FormListWithLetters с основой на сценарии по [ссылке ](https://docs.google.com/spreadsheets/d/1IHaHZS0_vT2SRZCWRdLPDvhNNvPcKf5QjA6GztFQgF4/edit#gid=208599158)

**Comment by SkinnerX7** [comment]
Связанная задача #6

**Comment by VladmirV** [comment]
Приступил к выполнению

**Comment by VladmirV** [comment]
Создана ветка issue-84

**Comment by VladmirV** [comment]
Реализованы тесты по [сценариям](https://docs.google.com/spreadsheets/d/1IHaHZS0_vT2SRZCWRdLPDvhNNvPcKf5QjA6GztFQgF4/edit#gid=208599158)
Результат:
![image](https://user-images.githubusercontent.com/55273743/83301517-7a143380-a202-11ea-8eb8-80329e670c06.png)
