### ISSUE TITLE
Разработка общего метода модуля — WorkWithLetters()

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#86]
Ваш модуль является звеном, соединяющий предыдущий и следующий.
WorkWithLetters() — метод, вызываемый у вас предыдущим модулем. После его вызова начинается работа вашего функционала, ваша зона ответственности

- Что на входе
Список экземпляров классов Letters с необработанной информацией

- Что требуется от вас
- - Принять данные от предыдущего модуля
- - Вытащить сырые данные и переконвертировать их к строковому в нужном формате
- - Сформировать JSON-ы с нужными данными по каждой лабораторной 
- -Отправить письма на проверку
- - Дождаться результатов проверки писем
- - Передать данные следующему модулю в формате списка экземпляров класса EmailResults

- Что на выходе
Вызов метода SetResults() с передачей в него сформированного списка 

Как это делать
- Данный метод показывает общий последовательный алгоритм работы модуля целиком
- Последовательное выполнение других методов внутри данного
- Вместо методов, которые реально выполняют то, что должны по функционалу, должны стоять заглушки по типу 
print ("Метод такой-то сделал то-то. После этого метода данные находятся (если есть какие-то общие переменные) в таком-то виде)")

Результат ожидается в виде модуля на языке python
Все имена функций и переменных будут являться стандартом и задачи будут назначаться непосредственно на реализацию конкретного метода.

**Comment by Progoger** [comment]
Написал метод WorkWithLetters
Постарался в комментариях объяснить все нюансы

**Comment by urec-programmec** [comment]
Принят pull request
Задача закрывается
