### ISSUE TITLE
Парсинг данных: GitHub

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#87]
Продемонстрировать работу по изучению языка python
Для этого:

Разработать метод, вытаскивающий данные из github по ссылке на репозиторий

Что на вход: 
Ссылка на репозиторий

Что на выходе
Единый текстовый файл (пока использовать запись в файл) с кодом, размещённым на github

Что предусмотреть
- Объединение кода из разных папок и документов в один
- Сопоставление (merging) заголовков (using ... )
- Изначально данные выгружаются из ветки master

Дополнительно
- Предусмотреть выгруз данных из других веток

Результаты представить в виде модуля на языке python, внутри которого располагается требуемый метод

**Comment by Progoger** [comment]
Добавил парсинг, пока только одного файла, если всё в порядке продолжаю работу

**Comment by Progoger** [comment]
Проверял парсинг на файлах по этим ссылкам:
https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/blob/Base/Server/HTTPReq.py
https://github.com/Students-of-the-city-of-Kostroma/trpo_automation/blob/Base/.gitignore

**Comment by Progoger** [comment]
Сделал открытие папок и файлов репозитория. Теперь все конечные файлы в папках и самом репозитории парсятся. Сделал чуть более понятную структуру, добавив вначале текста каждого файла его название

**Comment by urec-programmec** [comment]
Принял pull request
Задача закрывается
