### ISSUE TITLE
Разработка общего метода модуля - CheckEmail()

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#88]
Ваш модуль является звеном, соединяющий предыдущий и следующий.
CheckEmail() — метод, вызываемый у вас предыдущим модулем. После его вызова начинается работа вашего функционала, ваша зона ответственности

- Что на входе
Ничего, ваш модуль первый в цикле проверки писем

- Что требуется от вас
- - Проверить почту на предмет новых писем
- - Выгрузить данные с почты
- - Привести к единому виду информацию о пользователях — сформировать список экземпляров класса User
- - Привести к единому виду информацию о каждом письме — сформировать список экземпляров класса Letter
- - Провалидировать каждое письмо, дозаполнить нужные поля CodeStatus и CodeStatusComment
- - Передать данные следующему модулю в формате списка экземпляров класса Email

- Что на выходе
Вызов метода WorkWithLetters() с передачей в него сформированного списка

Как это делать
- Данный метод показывает общий последовательный алгоритм работы модуля целиком
- Последовательное выполнение других методов внутри данного
- Вместо методов, которые реально выполняют то, что должны по функционалу, должны стоять заглушки по типу 
print ("Метод такой-то сделал то-то. После этого метода данные находятся (если есть какие-то общие переменные) в таком-то виде)")

Результат ожидается в виде модуля на языке python
Все имена функций и переменных будут являться стандартом и задачи будут назначаться непосредственно на реализацию конкретного метода.

**Comment by cyberAndrey** [comment]
Работа готова к проверке. Результаты залил в ветку 88

**Comment by urec-programmec** [comment]
Задача потеряла актуальность
