### ISSUE TITLE
Сценарии на функцию MakeAnswersForUsers()

### ISSUE THREAD

**Issue by SkinnerX7** [Students-of-the-city-of-Kostroma/trpo_automation#89]
Переделать сценарии на функцию MakeAnswersForUsers(): [документ](https://docs.google.com/spreadsheets/d/1IHaHZS0_vT2SRZCWRdLPDvhNNvPcKf5QjA6GztFQgF4/edit#gid=208599158)

**Comment by SkinnerX7** [comment]
Готово для проверки
[Ссылка на документ](https://docs.google.com/spreadsheets/d/1IHaHZS0_vT2SRZCWRdLPDvhNNvPcKf5QjA6GztFQgF4/edit#gid=208599158)

**Comment by urec-programmec** [comment]
Отписал по комментариям

**Comment by urec-programmec** [comment]
Задача принимается
