### ISSUE TITLE
Валидация письма: Пользовательская документация

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#89]
Написать инструкцию по написанию писем для пользователей

На основании [документа](https://docs.google.com/document/d/1DRhgepxVwoscylIS2LCW-po5SFBdqOr-oo92bP_XfHE/edit) "Как писать письма" и написанного кода по валидации письма (задача #22) составить чёткую и понятную студентам записку о том, как именно должно быть написано письмо.

**Comment by cyberAndrey** [comment]
Задание [выполнил ](https://docs.google.com/document/d/1YMtlwsImBzR1ONhY6hH0VZnonpRmHM9UZ0glsG8sMLA/edit)

**Comment by urec-programmec** [comment]
Задачу подредактировал проверил
Принято
