### ISSUE TITLE
Сценарии тестирования функции FormsListWithLetters

### ISSUE THREAD

**Issue by SkinnerX7** [Students-of-the-city-of-Kostroma/trpo_automation#9]
Написать сценарии тестирования функции FormsListWithLetters по аналогии с уже существующими в [документе](https://docs.google.com/spreadsheets/d/1IHaHZS0_vT2SRZCWRdLPDvhNNvPcKf5QjA6GztFQgF4/edit?usp=sharing)
- Входные данные должны быть разного типа (как принимаемые для обработки этой функцией, так и непринимаемые)
- Входные данные должны быть корректными (ожидаемыми после отработки предыущей функции)
- В Input и в Output данные должны быть расписаны с нужной детализацией (важные в этой функции поля)

**Comment by VladmirV** [comment]
Сценарии на функцию FormsListWithLetters написаны по [ссылке](https://docs.google.com/spreadsheets/d/1IHaHZS0_vT2SRZCWRdLPDvhNNvPcKf5QjA6GztFQgF4/edit#gid=208599158)
@SkinnerX7 , ожидаю проверку.

**Comment by SkinnerX7** [comment]
Принял
