### ISSUE TITLE
Unittest'ы на функцию LettersConvertToString()

### ISSUE THREAD

**Issue by SkinnerX7** [Students-of-the-city-of-Kostroma/trpo_automation#90]
Что требуется:
- Посмотреть текущие unittest'ы на функцию
- Написать новые unittest'ы в соответствии со [сценариями](https://docs.google.com/spreadsheets/d/1IHaHZS0_vT2SRZCWRdLPDvhNNvPcKf5QjA6GztFQgF4/edit#gid=208599158)

**Comment by SkinnerX7** [comment]
Связанная задача #6

**Comment by SkinnerX7** [comment]
Задача закрывается, принят pr

**Comment by YuriSilenok** [comment]
В ветке issue-90 давно не было активности

**Comment by YuriSilenok** [comment]
Кажется, вы не удалили ветку issue-90 и закрыли задачу

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-90 давно не было активности
