### ISSUE TITLE
Скрипт - инсталлер

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#93]
Разработать консольный скрипт, устанавливающий и развёртывающий проект на машине.

Моделирование работы скрипта:
- получить изменения из ветки dev
- докачать необходимые файлы
- запустить все необходимые службы
- закрыться

**Comment by YuriSilenok** [comment]
Какие есть обновления по этой задаче?

**Comment by urec-programmec** [comment]
Включил дешифрование токенов и хранение их в зашифрованном виде на github

**Comment by YuriSilenok** [comment]
Вы не хотели бы поправить запрос #217 ?

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-93 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-93 давно не было активности

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-93 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-93 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-93 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-93 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-93 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-93 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-93 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-93 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-93 давно не было активности

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-93 давно не было активности

**Comment by YuriSilenok** [comment]
Задача с Вас снята, так как по ней давно не было активности.
