### ISSUE TITLE
Общий метод модуля: Создание метода

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#94]
Epic — #93 

Создать метод, принимающий на вход список экземпляров класса LetterResult.

Метод должен формировать список экземпляров класса AnswersForUsers в том же количестве, что длина входящего списка.

В конце метода должен вызваться метод InformUsers(), который должен быть описан ниже и ничего не делать, принимая на вход список экземпляров класса AnswersForUsers.

Метод должен ничего не возвращать.  

Классы AnswersForUsers и LetterResult реализованы в задаче #33 

Результат представить в виде модуля на языке python

**Comment by Kruuliter** [comment]
код сделан
куда заливать?

**Comment by Kruuliter** [comment]
задание сделано

**Comment by urec-programmec** [comment]
Задание проверил
Метод не соответствует требуемому в описании к задаче
Дальше:
- Изучить [диаграмму](https://app.diagrams.net/#G1uBk9EZCwKGp3pa4MURUgB9tz5a2x9DN_), оттуда взять функционал работы модуля
- Изучить пример такой же задачи у команды Base как пример хорошей реализации (Base -> BaseFunctions -> WorkWithLetters.py)

**Comment by urec-programmec** [comment]
Задача закрыта за потерей актуальности
