### ISSUE TITLE
Доделать проект для работы с группой ИС

### ISSUE THREAD

**Issue by DanilKozlov00** [Students-of-the-city-of-Kostroma/trpo_automation#94]
Соединить наш проект 18-ВТ с группой 18-ИС, проверить работоспособность, в случае ошибок разработать пути их решения, по возможности решить

**Comment by Dudka567** [comment]
Присутствовал при соединении клиента с сервером. Все прошло успешно. Уверяю!

**Comment by Llouqs** [comment]
Присутствовал при соединении клиента с сервером
