### ISSUE TITLE
Рефакторинг кода проекта

### ISSUE THREAD

**Issue by urec-programmec** [Students-of-the-city-of-Kostroma/trpo_automation#97]
Поправить многие места в коде

- удалить старый и неактуальный функционал
- поправить комментарии
- удалить ненужные файлы, сократить проект

**Comment by urec-programmec** [comment]
Задача закрывается, т.к. была реализована

**Comment by YuriSilenok** [comment]
Добрый день. Вы не удалили ветку issue-97 и закрыли задачу

**Comment by YuriSilenok** [comment]
Добрый день. В ветке issue-97 давно не было активности

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by YuriSilenok** [comment]
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

**Comment by urec-programmec** [comment]
Задача закрывается т.к. была реализована
